import { StrictMode, useState } from 'react';
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { LessonPlanWorkspace } from './LessonPlanWorkspace';
import { NavigationPreference } from '@/components/layout/NavigationPreference';
import { NavigationGuardProvider } from '@/services/navigation-guard';
import { lessonPlanApi } from '@/services/lesson-plans-api';
import type { LessonEvidenceView, LessonGenerationReceipt, LessonProposalView, LessonView } from '@/contracts/lesson-plans';
import { ApiError } from '@/services/api-client';
import { DocumentGateway } from './components/DocumentGateway';
import { useLessonEditor } from './model/EditorContext';
import { useLessonDocument } from './model/DocumentContext';
import { ProposalPanel } from './components/ProposalPanel';
import { DocumentsPanel } from './components/DocumentsPanel';
import { SourcePanel, initialGenerationInputs } from './components/SourcePanel';
import { LeaveProtection } from './components/LeaveProtection';
import type { DraftEnvelope, DraftRepository } from './model/types';
import { defaultSourceApi } from './model/workspace-services';
import type { AnalysisRunView, ClassReportRow, PracticeSetView } from '@/contracts/b4';
import type { ClassView } from '@/contracts/roster';
import type { ModelProfileView } from '@/contracts/model-settings';
import { emptyData } from './model/defaults';
import { LEGACY_KEY, serverSessionKey } from './model/server-cache';
import { exportDocx, exportPdf } from './services/export';

const router = vi.hoisted(() => ({ push: vi.fn(), replace: vi.fn() }));
vi.mock('next/navigation', () => ({ useRouter: () => router, usePathname: () => '/lesson-plans' }));
vi.mock('@/services/workflow-jobs-api', () => ({ observeJob: vi.fn(async () => null), retryObservationWindow: (view: { attempt: number }) => ({ minAttempt: view.attempt, maxAttempt: view.attempt + 1 }), retryJob: vi.fn(), cancelJob: vi.fn() }));
vi.mock('./services/export', async (load) => ({ ...await load<typeof import('./services/export')>(), exportDocx: vi.fn(async () => {}), exportPdf: vi.fn(async () => {}) }));
const analysis = { analysisRunId: 'run-fixed', inputHash: 'run-hash', scoreRevisionId: 'score-fixed', paperRevisionId: 'paper-fixed', className: null, classNameNote: '不带姓名', knowledgePoints: [{ knowledgePointId: 'kp-one', knowledgeRevisionId: 'kp-fixed', name: '依据语言', role: 'primary' as const }] };
function view(id = 'lesson-a', version = 1, title = '后台原文'): LessonView { const revisionId = `${id}-fixed-${version}`; return { protocolVersion: 2, lessonPlanId: id, subjectId: 'chinese', classId: 'class-a', revision: version, currentRevisionId: revisionId, replayed: false, currentRevision: { protocolVersion: 2, lessonPlanId: id, revisionId, version, data: { ...structuredClone(emptyData), title, reflection: '保留教学反思', lessonTypes: ['review', 'new'] }, contentHash: `hash-${version}`, source: 'manual', contextSnapshot: { subjectId: 'chinese', classId: 'class-a', classNameAtSave: '隔离班', analysis }, analysisRunId: 'run-fixed', acceptedProposalId: null, importEnvelope: null, selectedFields: [], processMetadata: [], reviewState: 'unreviewed', createdAt: '2026-10-03T00:00:00Z' } }; }
function page<T>(items: T[]) { return { items, total: items.length, offset: 0, limit: 50 }; }
function services(overrides: Partial<typeof lessonPlanApi> = {}) { return { ...lessonPlanApi, getLesson: vi.fn(async (id: string) => view(id)), listLessons: vi.fn(async () => page(['lesson-a', 'lesson-b'].map((id) => ({ lessonPlanId: id, subjectId: 'chinese', classId: 'class-a', revision: 1, currentRevisionId: `${id}-fixed-1`, title: id === 'lesson-a' ? '后台A' : '后台B', source: 'manual' as const, analysisRunId: 'run-fixed', updatedAt: '2026-10-03T00:00:00Z' })))), listLessonRevisions: vi.fn(async () => page([])), ...overrides }; }
function host(api: typeof lessonPlanApi, provider = false, extra: Record<string, string> = {}) { const workspace = <NavigationPreference><LessonPlanWorkspace initialLessonPlanId="lesson-a" services={{ lessonApi: api }} {...extra} /></NavigationPreference>; return render(provider ? <NavigationGuardProvider>{workspace}</NavigationGuardProvider> : workspace); }
beforeEach(() => {
  localStorage.clear(); router.push.mockClear(); router.replace.mockClear();
  Object.defineProperty(window, 'matchMedia', { configurable: true, value: vi.fn(() => ({ matches: false, addEventListener: vi.fn(), removeEventListener: vi.fn() })) });
  vi.stubGlobal('ResizeObserver', class { observe() {} disconnect() {} unobserve() {} });
  Object.defineProperty(HTMLDialogElement.prototype, 'showModal', { configurable: true, value() { this.setAttribute('open', ''); } }); Object.defineProperty(HTMLDialogElement.prototype, 'close', { configurable: true, value() { this.removeAttribute('open'); } });
  Element.prototype.scrollIntoView = vi.fn();
});
afterEach(() => { cleanup(); vi.useRealTimers(); vi.unstubAllGlobals(); vi.clearAllMocks(); localStorage.clear(); });
async function edit() { await screen.findByLabelText('课题'); fireEvent.change(screen.getByLabelText('课题'), { target: { value: '当前脏稿' } }); }

describe('F30-L actual workspace author UI checks', () => {
  it('standalone shell decision saves failure in place and permits cancelling without losing input', async () => {
    const saveLesson = vi.fn(async () => { throw new ApiError('WRITE_FAILED', '拒绝保存', 503, true); }); host(services({ saveLesson })); await edit(); fireEvent.click(screen.getByRole('button', { name: '学习问答' })); await screen.findByRole('dialog', { name: '离开当前教案' }); fireEvent.click(screen.getByRole('button', { name: '保存成功后离开' })); await screen.findByText(/保存失败，当前教案保持/); expect(screen.getByLabelText('课题')).toHaveValue('当前脏稿'); expect(router.push).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole('button', { name: '取消离开，继续编辑' })); expect(screen.queryByRole('dialog', { name: '离开当前教案' })).not.toBeInTheDocument(); expect(screen.getByLabelText('课题')).toHaveValue('当前脏稿');
  });
  it('real Provider protects shell with exactly one leave decision and preserves recovery cache', async () => {
    host(services(), true); await edit(); fireEvent.click(screen.getByRole('button', { name: '学习问答' })); await screen.findByRole('dialog', { name: '离开当前教案' }); fireEvent.click(screen.getByRole('button', { name: '保留恢复缓存后离开' })); await waitFor(() => expect(router.push).toHaveBeenCalledTimes(1)); expect(router.push).toHaveBeenCalledWith('/chat'); expect(screen.queryByRole('dialog', { name: '离开当前教案' })).not.toBeInTheDocument(); expect(JSON.parse(localStorage.getItem(serverSessionKey('lesson-a'))!).data.title).toBe('当前脏稿');
  });
  it('internal document switch cancel/keep/restore uses each independent server key', async () => {
    host(services()); await edit(); fireEvent.click(screen.getByRole('button', { name: '刷新后台列表' })); const second = await screen.findByRole('button', { name: /后台B/ }); fireEvent.click(second); await screen.findByRole('dialog', { name: '离开当前教案' }); fireEvent.click(screen.getByRole('button', { name: '取消离开，继续编辑' })); expect(screen.getByLabelText('课题')).toHaveValue('当前脏稿'); fireEvent.click(second); await screen.findByRole('dialog', { name: '离开当前教案' }); fireEvent.click(screen.getByRole('button', { name: '保留恢复缓存后离开' })); await waitFor(() => expect(screen.getByLabelText('课题')).toHaveValue('后台原文')); fireEvent.click(screen.getByRole('button', { name: '刷新后台列表' })); fireEvent.click(await screen.findByRole('button', { name: /后台A/ })); await waitFor(() => expect(screen.getByLabelText('课题')).toHaveValue('当前脏稿')); expect(localStorage.getItem(LEGACY_KEY)).toBeNull();
  });
  it('fixed history is readonly and copying becomes undoable current edit after latest read', async () => {
    const fixed = { ...view().currentRevision, revisionId: 'history-fixed', version: 0, data: { ...view().currentRevision.data, title: '固定历史正文' } }; host(services({ getLessonRevision: vi.fn(async () => fixed) }), false, { initialRevisionId: 'history-fixed' }); await screen.findByLabelText('课题'); expect(screen.getByLabelText('课题')).toBeDisabled(); expect(screen.getByLabelText('课题')).toHaveValue('固定历史正文'); fireEvent.click(screen.getByRole('button', { name: '打开当前版本准备复制历史正文' })); await screen.findByRole('button', { name: '明确复制历史正文到当前编辑' }); fireEvent.click(screen.getByRole('button', { name: '明确复制历史正文到当前编辑' })); await waitFor(() => expect(screen.getByLabelText('课题')).toHaveValue('固定历史正文')); expect(screen.getByRole('button', { name: '撤销' })).toBeEnabled(); fireEvent.click(screen.getByRole('button', { name: '撤销' })); expect(screen.getByLabelText('课题')).toHaveValue('后台原文');
  });
  it('print freezes data and source before the 100ms wait, including attempted edits', async () => {
    host(services()); await edit(); fireEvent.click(screen.getByRole('button', { name: '打印教案' })); await screen.findByText('导出一份可打印的教案'); vi.useFakeTimers(); fireEvent.click(screen.getByRole('button', { name: '打开打印窗口' })); expect(screen.getByLabelText('课题')).toBeDisabled(); fireEvent.change(screen.getByLabelText('课题'), { target: { value: '打印期间另改' } }); await act(async () => { vi.advanceTimersByTime(100); }); expect(exportPdf).toHaveBeenCalledWith(expect.stringContaining('当前脏稿 · 未保存编辑')); expect(screen.getByLabelText('课题')).toHaveValue('当前脏稿'); expect(screen.getAllByText(/当前脏稿/).length).toBeGreaterThan(1); act(() => window.dispatchEvent(new Event('afterprint'))); expect(screen.getByLabelText('课题')).toBeEnabled();
  });
  it('Word command receives frozen current data and exact source label', async () => {
    host(services()); await edit(); fireEvent.click(screen.getByRole('button', { name: '导出教案' })); fireEvent.click(screen.getByRole('button', { name: /导出 Word/ })); await waitFor(() => expect(exportDocx).toHaveBeenCalledTimes(1)); expect(exportDocx).toHaveBeenCalledWith(expect.objectContaining({ title: '当前脏稿', reflection: '保留教学反思' }), expect.stringContaining('未保存编辑 r1，基于 v1 · lesson-a-fixed-1'));
  });
  it('legacy local workspace still restores old key and manual edits use old local writer', async () => {
    localStorage.setItem(LEGACY_KEY, JSON.stringify({ schemaVersion: 1, revision: 9, updatedAt: '2026-10-03T00:00:00Z', data: { ...structuredClone(emptyData), title: '旧稿原文' } })); render(<NavigationPreference><LessonPlanWorkspace /></NavigationPreference>); await screen.findByLabelText('课题'); expect(screen.getByLabelText('课题')).toHaveValue('旧稿原文'); vi.useFakeTimers(); fireEvent.change(screen.getByLabelText('课题'), { target: { value: '旧稿新编辑' } }); await act(async () => { vi.advanceTimersByTime(600); }); expect(JSON.parse(localStorage.getItem(LEGACY_KEY)!).data.title).toBe('旧稿新编辑'); expect(Object.keys(localStorage).filter((key) => key.startsWith('zhiqikeyuan:lesson-plan:server-session:'))).toEqual([]);
  });
  it('empty legacy bytes are a visible read failure and editing cannot overwrite them', async () => { localStorage.setItem(LEGACY_KEY, ''); render(<NavigationPreference><LessonPlanWorkspace /></NavigationPreference>); await screen.findByLabelText('课题'); expect(screen.getByText('原草稿读取失败，自动保存已暂停。')).toBeInTheDocument(); vi.useFakeTimers(); fireEvent.change(screen.getByLabelText('课题'), { target: { value: '可备份的新输入' } }); await act(async () => { vi.advanceTimersByTime(700); }); expect(localStorage.getItem(LEGACY_KEY)).toBe(''); });
  it('missing legacy key still opens a normal local example without an error', async () => { render(<NavigationPreference><LessonPlanWorkspace /></NavigationPreference>); await screen.findByLabelText('课题'); expect(screen.getByLabelText('课题')).toHaveValue('荷塘月色'); expect(screen.queryByText('原草稿读取失败，自动保存已暂停。')).not.toBeInTheDocument(); });
  it.each(['with-document', 'without-document'])('invalid %s address blocks all dependent reads and local draft restoration', async (kind) => {
    const api = services(), repository = { load: vi.fn(() => null), save: vi.fn() }; const raw = '{ untouched legacy bytes'; localStorage.setItem(LEGACY_KEY, raw); render(<NavigationPreference><LessonPlanWorkspace initialLessonPlanId={kind === 'with-document' ? 'lesson-a' : undefined} initialRevisionId="invalid-fixed" initialRouteError="重复或缺少教案标识" services={{ lessonApi: api, repository }} /></NavigationPreference>); await screen.findByRole('alert'); expect(screen.getByText(/重复或缺少教案标识/)).toBeInTheDocument(); expect(api.getLesson).not.toHaveBeenCalled(); expect(repository.load).not.toHaveBeenCalled(); expect(repository.save).not.toHaveBeenCalled(); expect(screen.queryByLabelText('课题')).not.toBeInTheDocument(); expect(localStorage.getItem(LEGACY_KEY)).toBe(raw);
  });
  it('opening another backend document pushes its recoverable URL and a refreshed instance restores that document key', async () => {
    const api = services(); const first = host(api); await screen.findByLabelText('课题'); fireEvent.click(screen.getByRole('button', { name: '刷新后台列表' })); fireEvent.click(await screen.findByRole('button', { name: /后台B/ })); await waitFor(() => expect(router.push).toHaveBeenCalledWith('/lesson-plans?lessonPlanId=lesson-b')); await waitFor(() => expect(screen.getByLabelText('课题')).toHaveValue('后台原文')); fireEvent.change(screen.getByLabelText('课题'), { target: { value: 'B的恢复稿' } }); first.unmount(); render(<NavigationPreference><LessonPlanWorkspace initialLessonPlanId="lesson-b" services={{ lessonApi: api }} /></NavigationPreference>); await screen.findByLabelText('课题'); expect(screen.getByLabelText('课题')).toHaveValue('B的恢复稿'); expect(api.getLesson).toHaveBeenCalledWith('lesson-b', expect.any(AbortSignal));
  });
});

function leaveLocalDraft(): DraftEnvelope { return { schemaVersion: 1, revision: 9, updatedAt: '2026-10-03T00:00:00Z', data: { ...structuredClone(emptyData), title: '本地原稿' } }; }
function leaveRepository() {
  const original = leaveLocalDraft(); localStorage.setItem(LEGACY_KEY, JSON.stringify(original));
  return { load: vi.fn<DraftRepository['load']>(() => structuredClone(original)), save: vi.fn<DraftRepository['save']>((draft) => { localStorage.setItem(LEGACY_KEY, JSON.stringify(draft)); }) };
}
function leaveLocalHost(repository: DraftRepository, provider = false) { const workspace = <NavigationPreference><LessonPlanWorkspace services={{ repository, lessonApi: services() }} /></NavigationPreference>; return render(provider ? <NavigationGuardProvider>{workspace}</NavigationGuardProvider> : workspace); }
async function leaveEdit(title = '快速导航本地新稿') { await screen.findByLabelText('课题'); fireEvent.change(screen.getByLabelText('课题'), { target: { value: title } }); }
function LocalPendingLeaveHarness() {
  const editor = useLessonEditor(), doc = useLessonDocument(); const [result, setResult] = useState('尚未决定'), [, repaint] = useState(0);
  const pendingOperationRef = doc.pendingOperation;
  if (!editor.ready) return <p>正在恢复隔离本地稿</p>;
  return <><LeaveProtection /><input aria-label="本地保护正文" value={editor.data.title} onChange={(event) => editor.set({ title: event.target.value })} /><button onClick={() => { pendingOperationRef.current = { busy: true, unknown: false }; repaint((value) => value + 1); }}>设置创建在途</button><button onClick={() => { pendingOperationRef.current = { busy: false, unknown: true }; repaint((value) => value + 1); }}>设置导入未知</button><button onClick={async () => setResult(await doc.leave.current?.() ? '允许离开' : '保持当前稿')}>请求本地离开</button><output aria-label="本地离开结果">{result}</output></>;
}
function pendingLeaveHost(repository: DraftRepository) { return render(<NavigationPreference><DocumentGateway services={{ repository, lessonApi: services() }}><LocalPendingLeaveHarness /></DocumentGateway></NavigationPreference>); }
describe('F30-L v5 local navigation flush protects the actual serial writer', () => {
  it.each([false, true])('normal quick local navigation flushes first and leaves without a second decision, provider=%s', async (provider) => {
    const repository = leaveRepository(); leaveLocalHost(repository, provider); await leaveEdit(); fireEvent.click(screen.getByRole('button', { name: '学习问答' })); await waitFor(() => expect(router.push).toHaveBeenCalledWith('/chat')); expect(router.push).toHaveBeenCalledTimes(1); expect(repository.save).toHaveBeenCalledTimes(1); expect(repository.save.mock.calls[0][0]).toMatchObject({ schemaVersion: 1, revision: 10, data: { title: '快速导航本地新稿' } }); expect(JSON.parse(localStorage.getItem(LEGACY_KEY)!).data.title).toBe('快速导航本地新稿'); expect(screen.queryByRole('dialog', { name: '离开当前教案' })).not.toBeInTheDocument();
  });
  it('opening a backend document from local mode first persists the local draft without a manual leave promise', async () => {
    const repository = leaveRepository(); leaveLocalHost(repository); await leaveEdit(); fireEvent.click(screen.getByRole('button', { name: '刷新后台列表' })); fireEvent.click(await screen.findByRole('button', { name: /后台B/ })); await waitFor(() => expect(router.push).toHaveBeenCalledWith('/lesson-plans?lessonPlanId=lesson-b')); await waitFor(() => expect(screen.getByLabelText('课题')).toHaveValue('后台原文')); expect(JSON.parse(localStorage.getItem(LEGACY_KEY)!).data.title).toBe('快速导航本地新稿'); expect(repository.save).toHaveBeenCalledTimes(1); expect(screen.queryByRole('dialog', { name: '离开当前教案' })).not.toBeInTheDocument();
  });
  it('slow local persistence keeps navigation pending until its actual ACK', async () => {
    const repository = leaveRepository(); let finish!: () => void; repository.save.mockImplementationOnce((draft) => new Promise<void>((resolve) => { finish = () => { localStorage.setItem(LEGACY_KEY, JSON.stringify(draft)); resolve(); }; })); leaveLocalHost(repository); await leaveEdit(); fireEvent.click(screen.getByRole('button', { name: '学习问答' })); await waitFor(() => expect(repository.save).toHaveBeenCalledTimes(1)); expect(router.push).not.toHaveBeenCalled(); expect(JSON.parse(localStorage.getItem(LEGACY_KEY)!).data.title).toBe('本地原稿'); expect(screen.queryByRole('dialog', { name: '离开当前教案' })).not.toBeInTheDocument(); await act(async () => finish()); await waitFor(() => expect(router.push).toHaveBeenCalledTimes(1)); expect(JSON.parse(localStorage.getItem(LEGACY_KEY)!).data.title).toBe('快速导航本地新稿');
  });
  it('edits made during slow flush are written serially and newest input is saved before navigation', async () => {
    const repository = leaveRepository(); const finishes: (() => void)[] = []; repository.save.mockImplementation((draft) => new Promise<void>((resolve) => { finishes.push(() => { localStorage.setItem(LEGACY_KEY, JSON.stringify(draft)); resolve(); }); })); leaveLocalHost(repository); await leaveEdit('本地第一代'); fireEvent.click(screen.getByRole('button', { name: '学习问答' })); await waitFor(() => expect(repository.save).toHaveBeenCalledTimes(1)); fireEvent.change(screen.getByLabelText('课题'), { target: { value: '保存中编辑的第二代' } }); expect(repository.save.mock.calls[0][0]).toMatchObject({ revision: 10, data: { title: '本地第一代' } }); await act(async () => finishes[0]()); await waitFor(() => expect(repository.save).toHaveBeenCalledTimes(2)); expect(repository.save.mock.calls[1][0]).toMatchObject({ revision: 11, data: { title: '保存中编辑的第二代' } }); expect(router.push).not.toHaveBeenCalled(); await act(async () => finishes[1]()); await waitFor(() => expect(router.push).toHaveBeenCalledTimes(1)); expect(JSON.parse(localStorage.getItem(LEGACY_KEY)!)).toMatchObject({ revision: 11, data: { title: '保存中编辑的第二代' } });
  });
  it('late local flush cannot navigate after the workspace has adopted another document identity', async () => {
    const repository = leaveRepository(); let finish!: () => void; repository.save.mockImplementationOnce((draft) => new Promise<void>((resolve) => { finish = () => { localStorage.setItem(LEGACY_KEY, JSON.stringify(draft)); resolve(); }; })); const workspace = leaveLocalHost(repository); await leaveEdit(); fireEvent.click(screen.getByRole('button', { name: '学习问答' })); await waitFor(() => expect(repository.save).toHaveBeenCalledTimes(1)); workspace.rerender(<NavigationPreference><LessonPlanWorkspace initialLessonPlanId="lesson-b" services={{ repository, lessonApi: services() }} /></NavigationPreference>); await waitFor(() => expect(screen.getByLabelText('课题')).toHaveValue('后台原文')); await act(async () => finish()); expect(router.push).not.toHaveBeenCalled(); expect(screen.getByLabelText('课题')).toHaveValue('后台原文'); expect(JSON.parse(localStorage.getItem(LEGACY_KEY)!).data.title).toBe('快速导航本地新稿');
  });
  it.each(['retry', 'keep', 'discard', 'cancel'])('a failed local flush protects original input until explicit %s', async (decision) => {
    const repository = leaveRepository(); const raw = localStorage.getItem(LEGACY_KEY); repository.save.mockRejectedValueOnce(new Error('受控本地写入失败')); leaveLocalHost(repository); await leaveEdit(); fireEvent.click(screen.getByRole('button', { name: '学习问答' })); await screen.findByText(/保存失败，当前教案保持：受控本地写入失败/); await screen.findByRole('dialog', { name: '离开当前教案' }); expect(router.push).not.toHaveBeenCalled(); expect(screen.getByLabelText('课题')).toHaveValue('快速导航本地新稿'); expect(localStorage.getItem(LEGACY_KEY)).toBe(raw); expect(repository.save).toHaveBeenCalledTimes(1); const names = { retry: '保存成功后离开', keep: '保留恢复缓存后离开', discard: '明确放弃未保存编辑后离开', cancel: '取消离开，继续编辑' }; fireEvent.click(screen.getByRole('button', { name: names[decision as keyof typeof names] })); if (decision === 'cancel') { expect(router.push).not.toHaveBeenCalled(); expect(screen.getByLabelText('课题')).toHaveValue('快速导航本地新稿'); expect(localStorage.getItem(LEGACY_KEY)).toBe(raw); } else { await waitFor(() => expect(router.push).toHaveBeenCalledTimes(1)); if (decision === 'discard') { expect(repository.save).toHaveBeenCalledTimes(1); expect(localStorage.getItem(LEGACY_KEY)).toBe(raw); expect(screen.getByLabelText('课题')).toHaveValue('本地原稿'); } else { expect(repository.save).toHaveBeenCalledTimes(2); expect(repository.save.mock.calls[1][0]).toEqual(repository.save.mock.calls[0][0]); expect(JSON.parse(localStorage.getItem(LEGACY_KEY)!).data.title).toBe('快速导航本地新稿'); } } await waitFor(() => expect(screen.queryByRole('dialog', { name: '离开当前教案' })).not.toBeInTheDocument());
  });
  it('corrupt legacy bytes block automatic flush and cannot be replaced by a navigation attempt', async () => {
    const raw = '{ corrupt untouched local bytes'; localStorage.setItem(LEGACY_KEY, raw); render(<NavigationPreference><LessonPlanWorkspace /></NavigationPreference>); await leaveEdit('坏稿仍可备份的新输入'); fireEvent.click(screen.getByRole('button', { name: '学习问答' })); await screen.findByRole('dialog', { name: '离开当前教案' }); expect(screen.getByRole('button', { name: '保存成功后离开' })).toBeDisabled(); expect(screen.getByRole('button', { name: '保留恢复缓存后离开' })).toBeDisabled(); expect(screen.getByRole('button', { name: '明确放弃未保存编辑后离开' })).toBeDisabled(); expect(router.push).not.toHaveBeenCalled(); expect(localStorage.getItem(LEGACY_KEY)).toBe(raw); fireEvent.click(screen.getByRole('button', { name: '取消离开，继续编辑' })); expect(screen.getByLabelText('课题')).toHaveValue('坏稿仍可备份的新输入'); expect(localStorage.getItem(LEGACY_KEY)).toBe(raw);
  });
  it.each(['busy', 'unknown'])('local pending document operation %s skips automatic leave and preserves current input', async (kind) => {
    const repository = leaveRepository(); pendingLeaveHost(repository); await screen.findByLabelText('本地保护正文'); fireEvent.change(screen.getByLabelText('本地保护正文'), { target: { value: '原操作期间的新输入' } }); fireEvent.click(screen.getByRole('button', { name: kind === 'busy' ? '设置创建在途' : '设置导入未知' })); fireEvent.click(screen.getByRole('button', { name: '请求本地离开' })); await screen.findByRole('dialog', { name: '离开当前教案' }); expect(repository.save).not.toHaveBeenCalled(); expect(screen.getByRole('button', { name: '保存成功后离开' })).toBeDisabled(); expect(screen.getByRole('button', { name: '明确放弃未保存编辑后离开' })).toBeDisabled(); if (kind === 'busy') expect(screen.getByRole('button', { name: '保留恢复缓存后离开' })).toBeDisabled(); else expect(screen.getByText(/原操作结果未知/)).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: '取消离开，继续编辑' })); await screen.findByText('保持当前稿'); expect(screen.getByLabelText('本地保护正文')).toHaveValue('原操作期间的新输入');
  });
  it('a document operation becoming unknown during local flush prevents automatic permission', async () => {
    const repository = leaveRepository(); let finish!: () => void; repository.save.mockImplementationOnce((draft) => new Promise<void>((resolve) => { finish = () => { localStorage.setItem(LEGACY_KEY, JSON.stringify(draft)); resolve(); }; })); pendingLeaveHost(repository); await screen.findByLabelText('本地保护正文'); fireEvent.change(screen.getByLabelText('本地保护正文'), { target: { value: '未知操作之前的新稿' } }); fireEvent.click(screen.getByRole('button', { name: '请求本地离开' })); await waitFor(() => expect(repository.save).toHaveBeenCalledTimes(1)); fireEvent.click(screen.getByRole('button', { name: '设置导入未知' })); await act(async () => finish()); await screen.findByRole('dialog', { name: '离开当前教案' }); expect(screen.getByLabelText('本地离开结果')).toHaveTextContent('尚未决定'); expect(screen.getByRole('button', { name: '保存成功后离开' })).toBeDisabled(); expect(screen.getByRole('button', { name: '明确放弃未保存编辑后离开' })).toBeDisabled(); fireEvent.click(screen.getByRole('button', { name: '取消离开，继续编辑' })); await screen.findByText('保持当前稿');
  });
  it('printing begun while local flush is pending keeps the frozen print context and cancels navigation', async () => {
    const repository = leaveRepository(); let finish!: () => void; repository.save.mockImplementationOnce((draft) => new Promise<void>((resolve) => { finish = () => { localStorage.setItem(LEGACY_KEY, JSON.stringify(draft)); resolve(); }; })); leaveLocalHost(repository); await leaveEdit(); fireEvent.click(screen.getByRole('button', { name: '学习问答' })); await waitFor(() => expect(repository.save).toHaveBeenCalledTimes(1)); fireEvent.click(screen.getByRole('button', { name: '打印教案' })); await screen.findByText('导出一份可打印的教案'); fireEvent.click(screen.getByRole('button', { name: '打开打印窗口' })); expect(screen.getByLabelText('课题')).toBeDisabled(); await act(async () => finish()); expect(router.push).not.toHaveBeenCalled(); await screen.findByText('打印快照处理中，请完成打印后切换'); act(() => window.dispatchEvent(new Event('afterprint'))); expect(screen.getByLabelText('课题')).toBeEnabled();
  });
});

function NewDocumentHarness() { const doc = useLessonDocument(); return <><button onClick={() => doc.setSelection({ subjectId: 'chinese', classId: 'class-a', context: null })}>明确新文档来源</button><DocumentsPanel /></>; }
describe('F30-L create/import author UI checks', () => {
  it('successful create navigates to the actual backend document identity', async () => {
    const createLesson = vi.fn<typeof lessonPlanApi.createLesson>(async () => view('created-document')); render(<NavigationPreference><DocumentGateway services={{ lessonApi: services({ createLesson }) }}><NewDocumentHarness /></DocumentGateway></NavigationPreference>); fireEvent.click(screen.getByRole('button', { name: '明确新文档来源' })); fireEvent.click(screen.getByRole('button', { name: '创建空白后台教案' })); await waitFor(() => expect(router.push).toHaveBeenCalledWith('/lesson-plans?lessonPlanId=created-document')); expect(createLesson.mock.calls[0][0]).toMatchObject({ subjectId: 'chinese', classId: 'class-a', context: null, data: { title: '' }, submissionId: expect.any(String) });
  });
  it('strict whole legacy import sends full original envelope and leaves its raw key unchanged', async () => {
    const old = { schemaVersion: 1 as const, revision: 17, updatedAt: '2026-10-03T08:22:33+08:00', data: { ...structuredClone(emptyData), title: '完整旧本地稿', lessonTypes: ['review', 'new', 'review'] as const } }; const raw = JSON.stringify(old); localStorage.setItem(LEGACY_KEY, raw); const importLocalLesson = vi.fn<typeof lessonPlanApi.importLocalLesson>(async () => view('imported-document')); render(<NavigationPreference><DocumentGateway services={{ lessonApi: services({ importLocalLesson }) }}><NewDocumentHarness /></DocumentGateway></NavigationPreference>); fireEvent.click(screen.getByRole('button', { name: '明确新文档来源' })); fireEvent.click(screen.getByRole('button', { name: '导入完整旧本地稿到后台' })); await waitFor(() => expect(importLocalLesson).toHaveBeenCalledTimes(1)); expect(importLocalLesson.mock.calls[0][0].draft).toEqual(old); expect(localStorage.getItem(LEGACY_KEY)).toBe(raw); await waitFor(() => expect(router.push).toHaveBeenCalledWith('/lesson-plans?lessonPlanId=imported-document'));
  });
});

const scope = { schemaVersion: 2 as const, selection: { gradeId: 'grade', subjectId: 'chinese', editionId: 'edition', documentIds: ['textbook'] }, documents: [{ documentId: 'textbook', documentRevisionId: 'doc-fixed', metadataRevisionId: 'meta-fixed' }], embeddingGenerationId: 'embedding-fixed', scopeHash: 'scope-fixed' };
const refs = [{ evidenceId: 'ev-fixed', documentRevisionId: 'doc-fixed', normalizedTextSha256: 'sha-fixed', charStart: 0, charEnd: 10 }];
const evidence: LessonEvidenceView = { scopeSnapshot: scope, evidenceRefs: refs, evidence: [] };
function candidate(): LessonProposalView { return { protocolVersion: 2, lessonPlanId: 'lesson-a', proposalId: 'proposal-fixed', jobId: 'job-fixed', baseRevisionId: 'lesson-a-fixed-1', baseServerRevision: 1, inputHash: 'input-fixed', modelFingerprint: 'model-fixed', state: 'pending', patch: { coreCompetencies: 'AI核心', keyPoints: 'AI重点', teachingDesign: 'AI设计', process: ['导入', '探究', '练习', '总结'].map((stage, index) => ({ id: `ai-${index}`, stage, design: '课堂活动', secondary: '' })), exercises: 'AI练习' }, budget: { durationMinutes: 40, stages: ['introduction', 'exploration', 'practice', 'conclusion'].map((phase, index) => ({ processId: `ai-${index}`, phase: phase as 'introduction', minutes: 10, knowledgeAliases: ['K1'], activity: '活动', check: '检查', evidenceAliases: ['E1'] })) }, evidence: [{ alias: 'E1', kind: 'textbook', referenceId: 'ev-fixed', title: '隔离教材', sha256: 'sha-fixed', locator: {}, text: '教材依据' }], generationSource: { analysis, classId: 'class-a', selectedKnowledgePoints: analysis.knowledgePoints, modelProfileId: 'model-a', scopeSnapshot: scope, evidenceRefs: refs, requirements: '明确要求' }, selectedFields: [], acceptedRevisionId: null, createdAt: '2026-10-03T00:00:00Z', decidedAt: null, replayed: false }; }
function ProposalHarness() { const editor = useLessonEditor(), doc = useLessonDocument(); const [inputs, setInputs] = useState({ ...initialGenerationInputs, modelProfileId: 'model-a', requirements: '明确要求', evidence, classReady: true }); return <><input aria-label="测试正文" value={editor.data.title} onChange={(event) => editor.set({ title: event.target.value })} /><button onClick={() => setInputs({ ...inputs, modelProfileId: 'model-b' })}>测试切换模型</button><button onClick={() => setInputs({ ...inputs, modelProfileId: 'model-a' })}>测试恢复模型</button><button onClick={() => setInputs({ ...inputs, evidence: { ...evidence, scopeSnapshot: { ...scope, scopeHash: 'scope-other' }, evidenceRefs: [{ ...refs[0], evidenceId: 'ev-other' }] } })}>测试切换来源</button><button onClick={() => setInputs({ ...inputs, evidence })}>测试恢复来源</button><button onClick={editor.undo}>测试撤销</button><output>{editor.data.coreCompetencies} | {editor.data.reflection} | {doc.documentId}</output><ProposalPanel inputs={inputs} /></>; }
function proposalHost(api: typeof lessonPlanApi, recoveryStorage?: Storage) { return render(<NavigationPreference><DocumentGateway initialLessonPlanId="lesson-a" services={{ lessonApi: api, recoveryStorage }}><ProposalHarness /></DocumentGateway></NavigationPreference>); }
describe('F30-L proposal UI author checks', () => {
  it('five whole-field diff adopts only selected field in one undoable step', async () => {
    const applyLessonProposal = vi.fn<typeof lessonPlanApi.applyLessonProposal>(async () => { const next = view('lesson-a', 2); next.currentRevision.data.coreCompetencies = 'AI核心'; return next; }); const api = services({ generateLessonProposal: vi.fn(async () => ({ lessonPlanId: 'lesson-a', inputHash: 'input-fixed', job: { domain: 'teaching' as const, kind: 'lesson_generate', jobId: 'job-fixed', attempt: 1, state: 'succeeded' as const, result: { lessonPlanId: 'lesson-a', proposalId: 'proposal-fixed' }, error: null }, replayed: false })), getLessonProposal: vi.fn(async () => candidate()), applyLessonProposal }); proposalHost(api); await screen.findByLabelText('测试正文'); await waitFor(() => expect(screen.getByRole('button', { name: '保存当前稿并生成 AI 候选' })).toBeEnabled()); fireEvent.click(screen.getByRole('button', { name: '保存当前稿并生成 AI 候选' })); await screen.findByLabelText('采用核心素养'); expect(screen.getAllByText('当前正文')).toHaveLength(5); fireEvent.click(screen.getByLabelText('采用核心素养')); fireEvent.click(screen.getByRole('button', { name: '仅采用所选完整字段' })); await screen.findByText('AI核心 | 保留教学反思 | lesson-a'); expect(applyLessonProposal.mock.calls[0][2]).toMatchObject({ selectedFields: ['coreCompetencies'], expectedRevision: 1, baseRevisionId: 'lesson-a-fixed-1' }); fireEvent.click(screen.getByRole('button', { name: '测试撤销' })); expect(screen.getByText('| 保留教学反思 | lesson-a')).toBeInTheDocument();
  });
  it.each(['edit', 'model'])('a late successful candidate becomes visibly stale after %s', async (change) => {
    let complete!: (next: LessonProposalView) => void; const api = services({ generateLessonProposal: vi.fn(async () => ({ lessonPlanId: 'lesson-a', inputHash: 'input-fixed', job: { domain: 'teaching' as const, kind: 'lesson_generate', jobId: 'job-fixed', attempt: 1, state: 'succeeded' as const, result: { lessonPlanId: 'lesson-a', proposalId: 'proposal-fixed' }, error: null }, replayed: false })), getLessonProposal: vi.fn(() => new Promise<LessonProposalView>((resolve) => { complete = resolve; })) }); proposalHost(api); await screen.findByLabelText('测试正文'); await waitFor(() => expect(screen.getByRole('button', { name: '保存当前稿并生成 AI 候选' })).toBeEnabled()); fireEvent.click(screen.getByRole('button', { name: '保存当前稿并生成 AI 候选' })); await waitFor(() => expect(api.getLessonProposal).toHaveBeenCalledTimes(1)); if (change === 'edit') fireEvent.change(screen.getByLabelText('测试正文'), { target: { value: '后来新编辑' } }); else fireEvent.click(screen.getByRole('button', { name: '测试切换模型' })); await act(async () => complete(candidate())); await screen.findByText(/已过期：编辑或来源发生变化/); expect(screen.getByLabelText('采用核心素养')).toBeDisabled(); expect(screen.getByRole('button', { name: '仅采用所选完整字段' })).toBeDisabled();
  });
  it('explicit reject terminates the candidate without replacing any editor field', async () => { const rejectLessonProposal = vi.fn<typeof lessonPlanApi.rejectLessonProposal>(async () => ({ ...candidate(), state: 'rejected' })); const api = services({ generateLessonProposal: vi.fn(async () => ({ lessonPlanId: 'lesson-a', inputHash: 'input-fixed', job: { domain: 'teaching' as const, kind: 'lesson_generate', jobId: 'job-fixed', attempt: 1, state: 'succeeded' as const, result: { lessonPlanId: 'lesson-a', proposalId: 'proposal-fixed' }, error: null }, replayed: false })), getLessonProposal: vi.fn(async () => candidate()), rejectLessonProposal }); proposalHost(api); await screen.findByLabelText('测试正文'); await waitFor(() => expect(screen.getByRole('button', { name: '保存当前稿并生成 AI 候选' })).toBeEnabled()); fireEvent.click(screen.getByRole('button', { name: '保存当前稿并生成 AI 候选' })); await screen.findByRole('button', { name: '明确拒绝候选' }); fireEvent.click(screen.getByRole('button', { name: '明确拒绝候选' })); await screen.findByText(/固定候选 proposal-fixed · 已拒绝/); expect(screen.getByLabelText('测试正文')).toHaveValue('后台原文'); expect(screen.getByText('| 保留教学反思 | lesson-a')).toBeInTheDocument(); expect(rejectLessonProposal.mock.calls[0]).toEqual(['lesson-a', 'proposal-fixed', { submissionId: expect.any(String) }]); expect(screen.getByRole('button', { name: '明确拒绝候选' })).toBeDisabled(); });
});

function SourceHarness() { const [inputs, setInputs] = useState(initialGenerationInputs); return <><SourcePanel value={inputs} onChange={setInputs} /><output aria-label="已核验来源结果">{JSON.stringify(inputs)}</output></>; }
describe('F30-L source authority author UI check', () => {
  it('selects real fixed IDs and uses server verified scope/refs after actual source-span reads', async () => {
    const run: AnalysisRunView = { runId: 'run-fixed', assessmentId: 'assessment-fixed', subjectId: 'chinese', scoreRevisionId: 'score-fixed', paperRevisionId: 'paper-fixed', paperTitle: '固定原卷', inputHash: 'input-fixed', ruleCode: 'any_loss_v1', selectionSnapshot: { selectedParticipantIds: [], uniqueStudentCount: 0, participantCount: 0, leafCount: 0, stateCounts: { recorded: 0, missing: 0, absent: 0, exempt: 0 } }, participants: [], knowledgePoints: analysis.knowledgePoints, job: { jobId: 'analysis-job', domain: 'teaching', kind: 'analysis', attempt: 1, state: 'succeeded', result: null, error: null }, reportReady: true, createdAt: '2026-10-03T00:00:00Z' };
    const sourceApi = { ...defaultSourceApi,
      listClasses: vi.fn(async () => page([{ id: 'class-a', code: 'isolated', name: '隔离班', schoolYear: '2026', gradeId: 'grade', status: 'active' as const, revision: 1, studentCount: 0, createdAt: '2026-10-03T00:00:00Z' }])),
      taxonomy: vi.fn(async () => ({ stages: [], grades: [{ id: 'grade', label: '选定年级', stageId: 'stage' }], subjects: [{ id: 'chinese', label: '语文' }], editions: [{ id: 'edition', label: '选定版本' }] })), listProfiles: vi.fn(async () => []), listRuns: vi.fn(async () => page([run])), getRun: vi.fn(async () => run),
      listClassesReport: vi.fn(async () => page([{ classId: 'class-a', className: null, classNameNote: '脱敏', knowledgePoint: analysis.knowledgePoints[0], selectedCount: 0, validCount: 0, needsCount: 0, incompleteCount: 0, noEvidenceCount: 0, fullCreditCount: 0, numerator: 0, denominator: 0, ratio: null }])), listPractices: vi.fn(async () => page([])),
      listDocuments: vi.fn(async () => ({ documents: [{ documentId: 'textbook', ownerId: 'local-user' as const, title: '真实端口教材', libraryIds: [], gradeIds: ['grade'], subjectId: 'chinese', editionId: 'edition', metadataRevisionId: 'meta-fixed', currentRevision: { revisionId: 'doc-fixed', originalFileSha256: 'original-fixed', normalizedTextSha256: 'sha-fixed', parserVersion: 'fixture', charCount: 10, chunkCount: 1, createdAt: '2026-10-03T00:00:00Z' }, pendingRevisionId: null, deletedAt: null, revision: 1 }] })),
      getDocumentSource: vi.fn(async () => ({ documentRevisionId: 'doc-fixed', normalizedTextSha256: 'sha-fixed', charStart: 0, charEnd: 10, text: '0123456789', locator: { kind: 'markdown' as const, lineStart: 1, lineEnd: 1, pageStart: null, pageEnd: null, blockStart: null, blockEnd: null } })),
      listConfirmedQuestionRevisions: vi.fn(async () => page([{ questionId: 'question-variable', questionRevisionId: 'question-fixed-real', subjectId: 'chinese', stemMarkdown: '固定已确认题干' }])),
    };
    const verifyLessonEvidence = vi.fn<typeof lessonPlanApi.verifyLessonEvidence>(async () => ({ ...evidence, evidenceRefs: [{ ...refs[0], evidenceId: 'backend-verified-evidence' }] }));
    render(<NavigationPreference><DocumentGateway services={{ lessonApi: services({ verifyLessonEvidence }), sourceApi }}><SourceHarness /></DocumentGateway></NavigationPreference>); const panel = screen.getByText('班级、固定学情与生成来源').parentElement!; act(() => { panel.setAttribute('open', ''); panel.dispatchEvent(new Event('toggle')); }); await screen.findByRole('option', { name: '语文' }); fireEvent.change(screen.getByLabelText('教案学科'), { target: { value: 'chinese' } }); fireEvent.change(screen.getByLabelText('教案班级'), { target: { value: 'class-a' } }); fireEvent.change(screen.getByLabelText('固定学情报告'), { target: { value: 'run-fixed' } }); fireEvent.click(await screen.findByRole('checkbox', { name: /依据语言/ })); fireEvent.change(screen.getByLabelText('教材年级'), { target: { value: 'grade' } }); fireEvent.change(screen.getByLabelText('教材版本'), { target: { value: 'edition' } }); fireEvent.click(screen.getByRole('button', { name: '读取可选教材' })); await screen.findByRole('option', { name: /真实端口教材/ }); fireEvent.change(screen.getByLabelText('教材固定修订'), { target: { value: 'textbook' } }); fireEvent.change(screen.getByLabelText('切片终点'), { target: { value: '10' } }); fireEvent.click(screen.getByRole('button', { name: '读取并核验教材切片' })); await waitFor(() => expect(screen.getByLabelText('已核验来源结果').textContent).toContain('backend-verified-evidence')); expect(sourceApi.getDocumentSource).toHaveBeenCalledWith('doc-fixed', 0, 10); expect(verifyLessonEvidence).toHaveBeenCalledWith({ selection: { gradeId: 'grade', subjectId: 'chinese', editionId: 'edition', documentIds: ['textbook'] }, slices: [{ documentRevisionId: 'doc-fixed', charStart: 0, charEnd: 10 }] }); fireEvent.click(screen.getByRole('button', { name: '读取已确认固定题' })); fireEvent.click(await screen.findByRole('checkbox', { name: /固定已确认题干/ })); expect(JSON.parse(screen.getByLabelText('已核验来源结果').textContent!).questionRevisionIds).toEqual(['question-fixed-real']); expect(JSON.parse(screen.getByLabelText('已核验来源结果').textContent!).evidence.scopeSnapshot).toEqual(scope);
  });
});

function generationReceipt(jobId = 'job-fixed', state: 'succeeded' | 'queued' = 'succeeded'): LessonGenerationReceipt { return { lessonPlanId: 'lesson-a', inputHash: 'input-fixed', job: { domain: 'teaching', kind: 'lesson_generate', jobId, attempt: 1, state, result: state === 'succeeded' ? { lessonPlanId: 'lesson-a', proposalId: 'proposal-fixed' } : null, error: null }, replayed: false }; }
const generationKey = 'zhiqikeyuan:lesson-plan:generation:v1:lesson-a';
async function generateReady() { await screen.findByLabelText('测试正文'); const button = screen.getByRole('button', { name: '保存当前稿并生成 AI 候选' }); await waitFor(() => expect(button).toBeEnabled()); return button; }
describe('F30-L v2 generation first identity regression', () => {
  it.each(['model', 'source', 'edit', 'model-back', 'source-back'])('cancels a delayed save after %s and only an explicit new click sends the current package', async (change) => {
    let finishSave!: (next: LessonView) => void;
    const saveLesson = vi.fn<typeof lessonPlanApi.saveLesson>().mockImplementationOnce(() => new Promise((resolve) => { finishSave = resolve; })).mockImplementation(async (_id, body) => { const next = view('lesson-a', body.expectedRevision + 1, body.data.title); next.currentRevision.data = body.data; return next; });
    const generateLessonProposal = vi.fn<typeof lessonPlanApi.generateLessonProposal>(async () => generationReceipt('job-new', 'queued'));
    proposalHost(services({ saveLesson, generateLessonProposal })); const button = await generateReady(); fireEvent.change(screen.getByLabelText('测试正文'), { target: { value: '先保存的稿' } }); fireEvent.click(button); await waitFor(() => expect(saveLesson).toHaveBeenCalledTimes(1));
    if (change.startsWith('model')) { fireEvent.click(screen.getByRole('button', { name: '测试切换模型' })); if (change === 'model-back') fireEvent.click(screen.getByRole('button', { name: '测试恢复模型' })); }
    if (change.startsWith('source')) { fireEvent.click(screen.getByRole('button', { name: '测试切换来源' })); if (change === 'source-back') fireEvent.click(screen.getByRole('button', { name: '测试恢复来源' })); }
    if (change === 'edit') fireEvent.change(screen.getByLabelText('测试正文'), { target: { value: '保存之后的新稿' } });
    const saved = view('lesson-a', 2, '先保存的稿'); saved.currentRevision.data = saveLesson.mock.calls[0][1].data; await act(async () => finishSave(saved));
    await screen.findByText(/保存等待期间正文、来源或模型发生变化/); expect(generateLessonProposal).not.toHaveBeenCalled(); expect(screen.getByLabelText('测试正文')).toHaveValue(change === 'edit' ? '保存之后的新稿' : '先保存的稿');
    await waitFor(() => expect(screen.getByRole('button', { name: '保存当前稿并生成 AI 候选' })).toBeEnabled()); fireEvent.click(screen.getByRole('button', { name: '保存当前稿并生成 AI 候选' })); await waitFor(() => expect(generateLessonProposal).toHaveBeenCalledTimes(1)); const body = generateLessonProposal.mock.calls[0][1]; expect(body.modelProfileId).toBe(change === 'model' ? 'model-b' : 'model-a'); expect(body.scopeSnapshot.scopeHash).toBe(change === 'source' ? 'scope-other' : 'scope-fixed'); expect(body.baseServerRevision).toBe(change === 'edit' ? 3 : 2); expect(body.baseRevisionId).toBe(`lesson-a-fixed-${change === 'edit' ? 3 : 2}`);
  });
  it.each(['model', 'model-back', 'source-back'])('unknown response replay retains the first body and becomes stale after %s', async (change) => {
    const observedRecords: unknown[] = [];
    const generateLessonProposal = vi.fn<typeof lessonPlanApi.generateLessonProposal>().mockImplementationOnce(async () => { observedRecords.push(JSON.parse(localStorage.getItem(generationKey)!)); throw new ApiError('NETWORK_ERROR', '首个202响应丢失', 0, true); }).mockImplementation(async () => { observedRecords.push(JSON.parse(localStorage.getItem(generationKey)!)); return generationReceipt(); });
    const api = services({ generateLessonProposal, getLessonProposal: vi.fn(async () => candidate()), applyLessonProposal: vi.fn(async () => view('lesson-a', 2)) }); proposalHost(api); fireEvent.click(await generateReady()); const retry = await screen.findByRole('button', { name: '重试原生成包' }); await waitFor(() => expect(retry).toBeEnabled());
    if (change.startsWith('model')) { fireEvent.click(screen.getByRole('button', { name: '测试切换模型' })); if (change === 'model-back') fireEvent.click(screen.getByRole('button', { name: '测试恢复模型' })); } else { fireEvent.click(screen.getByRole('button', { name: '测试切换来源' })); fireEvent.click(screen.getByRole('button', { name: '测试恢复来源' })); }
    fireEvent.click(retry); await screen.findByText(/固定候选 proposal-fixed · 已过期/); expect(generateLessonProposal.mock.calls[1]).toEqual(generateLessonProposal.mock.calls[0]); expect(generateLessonProposal.mock.calls[1][1].modelProfileId).toBe('model-a'); expect(observedRecords[1]).toEqual(observedRecords[0]); expect(screen.getByLabelText('采用核心素养')).toBeDisabled(); expect(screen.getByRole('button', { name: '仅采用所选完整字段' })).toBeDisabled(); expect(api.applyLessonProposal).not.toHaveBeenCalled();
  });
  it('a recovered unknown operation replays its body and remains conservative after reload', async () => {
    const generateLessonProposal = vi.fn<typeof lessonPlanApi.generateLessonProposal>().mockRejectedValueOnce(new ApiError('NETWORK_ERROR', '202未知', 0, true)).mockImplementation(async () => generationReceipt()); const api = services({ generateLessonProposal, getLessonProposal: vi.fn(async () => candidate()) }); const first = proposalHost(api); fireEvent.click(await generateReady()); await screen.findByRole('button', { name: '重试原生成包' }); const originalRecord = JSON.parse(localStorage.getItem(generationKey)!); first.unmount(); proposalHost(api); await screen.findByLabelText('测试正文'); const retry = await screen.findByRole('button', { name: '重试原生成包' }); await waitFor(() => expect(retry).toBeEnabled()); fireEvent.click(retry); await screen.findByText(/固定候选 proposal-fixed · 已过期/); expect(generateLessonProposal.mock.calls[1]).toEqual(generateLessonProposal.mock.calls[0]); expect(JSON.parse(localStorage.getItem(generationKey)!).operation.metadata).toEqual(originalRecord.operation.metadata); expect(screen.getByRole('button', { name: '仅采用所选完整字段' })).toBeDisabled();
  });
  it('an in-flight candidate stays stale after model A to B to A', async () => {
    let finish!: (next: LessonGenerationReceipt) => void; const generateLessonProposal = vi.fn<typeof lessonPlanApi.generateLessonProposal>(() => new Promise((resolve) => { finish = resolve; })); proposalHost(services({ generateLessonProposal, getLessonProposal: vi.fn(async () => candidate()) })); fireEvent.click(await generateReady()); await waitFor(() => expect(generateLessonProposal).toHaveBeenCalledTimes(1)); fireEvent.click(screen.getByRole('button', { name: '测试切换模型' })); fireEvent.click(screen.getByRole('button', { name: '测试恢复模型' })); await act(async () => finish(generationReceipt())); await screen.findByText(/固定候选 proposal-fixed · 已过期/); expect(screen.getByLabelText('采用核心素养')).toBeDisabled();
  });
  it('a late old proposal read cannot attach to a new queued generation', async () => {
    let finishOld!: (next: LessonProposalView) => void; const getLessonProposal = vi.fn<typeof lessonPlanApi.getLessonProposal>(() => new Promise((resolve) => { finishOld = resolve; })); const generateLessonProposal = vi.fn<typeof lessonPlanApi.generateLessonProposal>().mockResolvedValueOnce(generationReceipt()).mockResolvedValueOnce(generationReceipt('job-new', 'queued')); proposalHost(services({ getLessonProposal, generateLessonProposal })); fireEvent.click(await generateReady()); await waitFor(() => expect(getLessonProposal).toHaveBeenCalledTimes(1)); fireEvent.click(screen.getByRole('button', { name: '测试切换模型' })); fireEvent.click(screen.getByRole('button', { name: '保存当前稿并生成 AI 候选' })); await screen.findByText(/任务：已排队.*job-new/); await act(async () => finishOld(candidate())); expect(screen.queryByLabelText('采用核心素养')).not.toBeInTheDocument(); expect(generateLessonProposal.mock.calls[1][1].modelProfileId).toBe('model-b');
  });
  it('a recovered source record with the same operation ID but different first metadata pauses replay without overwriting either cache', async () => {
    const generateLessonProposal = vi.fn<typeof lessonPlanApi.generateLessonProposal>().mockRejectedValue(new ApiError('NETWORK_ERROR', '202未知', 0, true)); const api = services({ generateLessonProposal }); const first = proposalHost(api); fireEvent.click(await generateReady()); await screen.findByRole('button', { name: '重试原生成包' }); first.unmount(); const sourceRecord = JSON.parse(localStorage.getItem(generationKey)!); sourceRecord.operation.metadata.originalEditGeneration += 1; const raw = JSON.stringify(sourceRecord); localStorage.setItem(generationKey, raw); const originalServer = localStorage.getItem(serverSessionKey('lesson-a')); proposalHost(api); await screen.findByText(/生成观察恢复读取失败/); expect(screen.getByRole('button', { name: '重试原生成包' })).toBeDisabled(); expect(generateLessonProposal).toHaveBeenCalledTimes(1); expect(localStorage.getItem(generationKey)).toBe(raw); expect(localStorage.getItem(serverSessionKey('lesson-a'))).toBe(originalServer);
  });
});

function fixedRun(): AnalysisRunView { return { runId: 'run-fixed', assessmentId: 'assessment-fixed', subjectId: 'chinese', scoreRevisionId: 'score-fixed', paperRevisionId: 'paper-fixed', paperTitle: '固定原卷', inputHash: 'input-fixed', ruleCode: 'any_loss_v1', selectionSnapshot: { selectedParticipantIds: [], uniqueStudentCount: 0, participantCount: 0, leafCount: 0, stateCounts: { recorded: 0, missing: 0, absent: 0, exempt: 0 } }, participants: [], knowledgePoints: analysis.knowledgePoints, job: { jobId: 'analysis-job', domain: 'teaching', kind: 'analysis', attempt: 1, state: 'succeeded', result: null, error: null }, reportReady: true, createdAt: '2026-10-03T00:00:00Z' }; }
function reportRow(classId: string): ClassReportRow { return { classId, className: null, classNameNote: '脱敏', knowledgePoint: analysis.knowledgePoints[0], selectedCount: 0, validCount: 0, needsCount: 0, incompleteCount: 0, noEvidenceCount: 0, fullCreditCount: 0, numerator: 0, denominator: 0, ratio: null }; }
function pagedSources(read: typeof defaultSourceApi.listClassesReport) { return { ...defaultSourceApi, listClasses: vi.fn(async () => page([])), taxonomy: vi.fn(async () => ({ stages: [], grades: [], subjects: [], editions: [] })), listProfiles: vi.fn(async () => []), listRuns: vi.fn(async () => page([fixedRun()])), getRun: vi.fn(async () => fixedRun()), listPractices: vi.fn(async () => page([])), listClassesReport: read }; }
function sourceHost(sourceApi: typeof defaultSourceApi) { render(<NavigationPreference><DocumentGateway initialLessonPlanId="lesson-a" services={{ lessonApi: services(), sourceApi }}><SourceHarness /></DocumentGateway></NavigationPreference>); }
async function openSourcePanel() { const summary = await screen.findByText('班级、固定学情与生成来源'); act(() => { const panel = summary.parentElement!; panel.setAttribute('open', ''); panel.dispatchEvent(new Event('toggle')); }); }
describe('F30-L v2 complete report source pagination', () => {
  it('uses the real 200-row maximum and finds the target class after duplicated class-KP rows', async () => {
    const rows = [...Array.from({ length: 200 }, () => reportRow('class-other')), reportRow('class-a')]; const listClassesReport = vi.fn<typeof defaultSourceApi.listClassesReport>(async (_id, query) => { if (!query?.limit || query.limit > 200) throw new ApiError('VALIDATION', '真实上限200', 422, false); const offset = query.offset ?? 0; return { items: rows.slice(offset, offset + query.limit), total: rows.length, offset, limit: query.limit }; }); sourceHost(pagedSources(listClassesReport)); await openSourcePanel(); await screen.findByRole('checkbox', { name: /依据语言/ }); await waitFor(() => expect(JSON.parse(screen.getByLabelText('已核验来源结果').textContent!).classReady).toBe(true)); expect(listClassesReport.mock.calls).toEqual([['run-fixed', { offset: 0, limit: 200 }], ['run-fixed', { offset: 200, limit: 200 }]]); expect(screen.queryByText('所选班级不在固定报告中，生成暂停。')).not.toBeInTheDocument();
    const hint = screen.getByText('请勿填写学生姓名、学号或人员 ID；已知身份将被阻断，系统不能保证识别全部个人信息。'); expect(hint).toBeVisible(); expect(screen.getByLabelText('教案生成要求')).toHaveAttribute('aria-describedby', hint.id);
  });
  it.each(['failure', 'empty', 'invalid-total', 'changed-total'])('keeps a later-page %s visible without adopting incomplete source', async (fault) => {
    const listClassesReport = vi.fn<typeof defaultSourceApi.listClassesReport>(async (_id, query) => { const offset = query?.offset ?? 0; if (!offset) return { items: Array.from({ length: 200 }, () => reportRow('class-other')), total: 201, offset, limit: 200 }; if (fault === 'failure') throw new ApiError('READ_FAILED', '后页读取失败', 503, true); return { items: fault === 'empty' ? [] : [reportRow('class-a')], total: fault === 'invalid-total' ? Number.NaN : fault === 'changed-total' ? 202 : 201, offset, limit: 200 }; }); sourceHost(pagedSources(listClassesReport)); await openSourcePanel(); await screen.findByRole('alert'); expect(screen.getByRole('alert').textContent).toMatch(fault === 'failure' ? /后页读取失败/ : /分页/); expect(listClassesReport).toHaveBeenCalledTimes(2); expect(JSON.parse(screen.getByLabelText('已核验来源结果').textContent!).classReady).toBe(false); expect(screen.queryByRole('checkbox', { name: /依据语言/ })).not.toBeInTheDocument();
  });
});

function CopyControllerHarness({ decision = async () => false }: { decision?: () => Promise<boolean> }) { const doc = useLessonDocument(), editor = useLessonEditor(), leaveRef = doc.leave; return <><output aria-label="复制目标">{doc.documentId ?? 'local'} | {doc.pendingCopy?.lessonPlanId ?? '-'} | {doc.pendingCopy?.revisionId ?? '-'}</output><button onClick={() => { leaveRef.current = decision; }}>取消下一次离开</button><button onClick={() => void doc.openDocument('lesson-b')}>打开B</button><button onClick={() => void doc.openDocument('lesson-a', 'other-history')}>打开另一个历史</button><button onClick={() => void doc.openLocal()}>打开本地</button><button onClick={() => editor.history && void doc.copyHistory(editor.history)}>准备复制</button></>; }
describe('F30-L v2 history copy target ownership', () => {
  it('retains same-document copy across the actual initial props change and clears it on the next history', async () => {
    const fixed = { ...view().currentRevision, revisionId: 'history-fixed', version: 0, data: { ...view().currentRevision.data, title: '历史A正文' } }; const api = services({ getLessonRevision: vi.fn(async (_id, revisionId) => ({ ...fixed, revisionId })) }); const props = { services: { lessonApi: api }, initialLessonPlanId: 'lesson-a' }; const current = render(<NavigationPreference><LessonPlanWorkspace {...props} initialRevisionId="history-fixed" /></NavigationPreference>); await screen.findByLabelText('课题'); fireEvent.click(screen.getByRole('button', { name: '打开当前版本准备复制历史正文' })); await screen.findByRole('button', { name: '明确复制历史正文到当前编辑' }); current.rerender(<NavigationPreference><LessonPlanWorkspace {...props} /></NavigationPreference>); expect(screen.getByRole('button', { name: '明确复制历史正文到当前编辑' })).toBeInTheDocument(); current.rerender(<NavigationPreference><LessonPlanWorkspace {...props} initialRevisionId="other-history" /></NavigationPreference>); await waitFor(() => expect(screen.getByLabelText('课题')).toBeDisabled()); expect(screen.queryByRole('button', { name: '明确复制历史正文到当前编辑' })).not.toBeInTheDocument();
  });
  it.each(['打开B', '打开另一个历史', '打开本地'])('clears the matching A intent when %s succeeds', async (next) => {
    const api = services({ getLessonRevision: vi.fn(async (id, revisionId) => ({ ...view(id).currentRevision, revisionId })) }); render(<NavigationPreference><DocumentGateway initialLessonPlanId="lesson-a" initialRevisionId="history-fixed" services={{ lessonApi: api }}><CopyControllerHarness /></DocumentGateway></NavigationPreference>); await screen.findByLabelText('复制目标'); fireEvent.click(screen.getByRole('button', { name: '准备复制' })); await waitFor(() => expect(screen.getByLabelText('复制目标').textContent).toBe('lesson-a | lesson-a | history-fixed')); fireEvent.click(screen.getByRole('button', { name: next })); await waitFor(() => expect(screen.getByLabelText('复制目标').textContent).toBe(`${next === '打开B' ? 'lesson-b' : next === '打开本地' ? 'local' : 'lesson-a'} | - | -`));
  });
  it('a cancelled history-to-current leave never installs a copy intent', async () => {
    const api = services({ getLessonRevision: vi.fn(async () => ({ ...view().currentRevision, revisionId: 'history-fixed' })) }); render(<NavigationPreference><DocumentGateway initialLessonPlanId="lesson-a" initialRevisionId="history-fixed" services={{ lessonApi: api }}><CopyControllerHarness /></DocumentGateway></NavigationPreference>); await screen.findByLabelText('复制目标'); fireEvent.click(screen.getByRole('button', { name: '取消下一次离开' })); fireEvent.click(screen.getByRole('button', { name: '准备复制' })); await act(async () => {}); expect(screen.getByLabelText('复制目标').textContent).toBe('lesson-a | - | -'); expect(router.push).not.toHaveBeenCalled();
  });
  it('a late leave confirmation from history A cannot navigate back after route props selected B', async () => {
    let confirm!: (allowed: boolean) => void; const decision = vi.fn(() => new Promise<boolean>((resolve) => { confirm = resolve; })); const api = services({ getLessonRevision: vi.fn(async () => ({ ...view().currentRevision, revisionId: 'history-fixed' })) }); const initial = render(<NavigationPreference><DocumentGateway initialLessonPlanId="lesson-a" initialRevisionId="history-fixed" services={{ lessonApi: api }}><CopyControllerHarness decision={decision} /></DocumentGateway></NavigationPreference>); await screen.findByLabelText('复制目标'); fireEvent.click(screen.getByRole('button', { name: '取消下一次离开' })); fireEvent.click(screen.getByRole('button', { name: '准备复制' })); expect(decision).toHaveBeenCalledTimes(1); initial.rerender(<NavigationPreference><DocumentGateway initialLessonPlanId="lesson-b" services={{ lessonApi: api }}><CopyControllerHarness decision={decision} /></DocumentGateway></NavigationPreference>); await waitFor(() => expect(screen.getByLabelText('复制目标').textContent).toBe('lesson-b | - | -')); await act(async () => confirm(true)); expect(screen.getByLabelText('复制目标').textContent).toBe('lesson-b | - | -'); expect(router.push).not.toHaveBeenCalled();
  });
});

describe('F30-L v3 candidate owns its first generation identity', () => {
  it.each(['422', '503', 'unknown', 'cache'])('a new M2 generation %s cannot revive selected M1 fields', async (failure) => {
    let blockSourceCache = false;
    const storage: Storage = { get length() { return localStorage.length; }, key: (index) => localStorage.key(index), clear: () => localStorage.clear(), removeItem: (key) => localStorage.removeItem(key), getItem: (key) => localStorage.getItem(key), setItem(key, raw) { if (blockSourceCache && key === generationKey) throw new DOMException('隔离来源写入失败', 'QuotaExceededError'); localStorage.setItem(key, raw); } };
    const generateLessonProposal = vi.fn<typeof lessonPlanApi.generateLessonProposal>().mockResolvedValueOnce(generationReceipt()).mockRejectedValueOnce(new ApiError('GENERATE_FAILED', `M2新生成失败 ${failure}`, failure === 'unknown' ? 0 : failure === '503' ? 503 : 422, true)).mockResolvedValueOnce(generationReceipt('job-m2', 'queued'));
    const applyLessonProposal = vi.fn<typeof lessonPlanApi.applyLessonProposal>(async () => view('lesson-a', 2)); const rejectLessonProposal = vi.fn<typeof lessonPlanApi.rejectLessonProposal>(async () => ({ ...candidate(), state: 'rejected' }));
    proposalHost(services({ generateLessonProposal, getLessonProposal: vi.fn(async () => candidate()), applyLessonProposal, rejectLessonProposal }), storage); fireEvent.click(await generateReady()); const selected = await screen.findByLabelText('采用核心素养'); fireEvent.click(selected); expect(selected).toBeChecked(); fireEvent.click(screen.getByRole('button', { name: '测试切换模型' })); await screen.findByText(/固定候选 proposal-fixed · 已过期/); blockSourceCache = failure === 'cache'; fireEvent.click(screen.getByRole('button', { name: '保存当前稿并生成 AI 候选' })); if (failure === 'unknown') await screen.findByRole('button', { name: '重试原生成包' }); else await screen.findByText(failure === 'cache' ? /首次生成来源签名写入失败/ : new RegExp(`M2新生成失败 ${failure}`));
    expect(screen.getByText(/固定候选 proposal-fixed · 已过期/)).toBeInTheDocument(); expect(screen.getByLabelText('采用核心素养')).toBeChecked(); expect(screen.getByLabelText('采用核心素养')).toBeDisabled(); const apply = screen.getByRole('button', { name: '仅采用所选完整字段' }); expect(apply).toBeDisabled(); fireEvent.click(apply); expect(applyLessonProposal).not.toHaveBeenCalled(); expect(screen.getByLabelText('测试正文')).toHaveValue('后台原文'); expect(screen.getByText('| 保留教学反思 | lesson-a')).toBeInTheDocument();
    if (failure === 'cache') expect(generateLessonProposal).toHaveBeenCalledTimes(1);
    else expect(generateLessonProposal.mock.calls[1][1].modelProfileId).toBe('model-b');
    if (failure === '422' || failure === '503') { fireEvent.click(screen.getByRole('button', { name: '明确拒绝候选' })); await screen.findByText(/固定候选 proposal-fixed · 已拒绝/); expect(rejectLessonProposal).toHaveBeenCalledWith('lesson-a', 'proposal-fixed', { submissionId: expect.any(String) }); }
    if (failure === 'unknown') { const firstM2 = JSON.parse(localStorage.getItem(generationKey)!); const retry = screen.getByRole('button', { name: '重试原生成包' }); await waitFor(() => expect(retry).toBeEnabled()); fireEvent.click(retry); await screen.findByText(/任务：已排队.*job-m2/); expect(generateLessonProposal.mock.calls[2]).toEqual(generateLessonProposal.mock.calls[1]); expect(JSON.parse(localStorage.getItem(generationKey)!).operation).toEqual(firstM2.operation); expect(applyLessonProposal).not.toHaveBeenCalled(); }
  });
});

function classItem(index: number): ClassView { return { id: `class-${index}`, code: `isolated-${index}`, name: `班级${index}`, schoolYear: '2026', gradeId: 'grade', status: 'active', revision: 1, studentCount: 0, createdAt: '2026-10-03T00:00:00Z' }; }
function practiceItem(index: number): PracticeSetView { const revision = { practiceSetId: `practice-${index}`, practiceRevisionId: `practice-fixed-${index}`, version: 1, state: index === 241 ? 'reviewed' as const : 'draft' as const, title: `固定练习${index}`, subjectId: 'chinese', analysisRunId: 'run-241', targetKnowledgePoints: analysis.knowledgePoints, constraints: { count: 1 }, inputHash: `practice-input-${index}`, totalScoreUnits: 0, draftItems: [], items: [], reviewedAt: index === 241 ? '2026-10-03T00:00:00Z' : null, createdAt: '2026-10-03T00:00:00Z' }; return { practiceSetId: revision.practiceSetId, title: revision.title, subjectId: 'chinese', analysisRunId: 'run-241', revision: 1, currentRevision: revision, revisions: [revision], replayed: false }; }
type SourceList = 'classes' | 'runs' | 'practices';
type SourceFault = 'failure' | 'empty' | 'invalid-total' | 'changed-total' | 'wrong-offset';
function realPage<T>(rows: T[], query: { offset?: number; limit?: number } = {}, fault?: SourceFault) {
  if (!query.limit || query.limit > 200) throw new ApiError('VALIDATION', '真实公开上限200', 422, false);
  const offset = query.offset ?? 0;
  if (offset > 0 && fault === 'failure') throw new ApiError('READ_FAILED', '后页读取失败，未采用半份来源', 503, true);
  return { items: offset > 0 && fault === 'empty' ? [] : rows.slice(offset, offset + query.limit), total: offset > 0 && fault === 'invalid-total' ? Number.NaN : offset > 0 && fault === 'changed-total' ? rows.length + 1 : rows.length, offset: offset > 0 && fault === 'wrong-offset' ? 0 : offset, limit: query.limit };
}
function completeSourceFixture(broken?: SourceList, fault?: SourceFault) {
  const classes = Array.from({ length: 241 }, (_, index) => classItem(index + 1)); const runs = Array.from({ length: 241 }, (_, index) => ({ ...fixedRun(), runId: `run-${index + 1}`, paperTitle: `报告${index + 1}`, reportReady: index === 240 })); const practices = Array.from({ length: 241 }, (_, index) => practiceItem(index + 1));
  return { ...defaultSourceApi, listClasses: vi.fn<typeof defaultSourceApi.listClasses>(async (query) => realPage(classes, query, broken === 'classes' ? fault : undefined)), taxonomy: vi.fn(async () => ({ stages: [], grades: [], subjects: [{ id: 'chinese', label: '语文' }], editions: [] })), listProfiles: vi.fn(async () => []), listRuns: vi.fn<typeof defaultSourceApi.listRuns>(async (query) => realPage(runs, query, broken === 'runs' ? fault : undefined)), getRun: vi.fn(async () => runs[240]), listClassesReport: vi.fn(async () => page([reportRow('class-241')])), listPractices: vi.fn<typeof defaultSourceApi.listPractices>(async (query) => realPage(practices, query, broken === 'practices' ? fault : undefined)) };
}
function localSourceHost(sourceApi: typeof defaultSourceApi) { return render(<NavigationPreference><DocumentGateway services={{ lessonApi: services(), sourceApi }}><SourceHarness /></DocumentGateway></NavigationPreference>); }
async function chooseLaterReport() { await screen.findByRole('option', { name: '班级241' }); fireEvent.change(screen.getByLabelText('教案学科'), { target: { value: 'chinese' } }); fireEvent.change(screen.getByLabelText('教案班级'), { target: { value: 'class-241' } }); fireEvent.change(screen.getByLabelText('固定学情报告'), { target: { value: 'run-241' } }); }
describe('F30-L v3 complete selectable source lists', () => {
  it('selects the 241st class, ready report and reviewed fixed practice through strict real-sized pages', async () => {
    const sources = completeSourceFixture(); localSourceHost(sources); await openSourcePanel(); await chooseLaterReport(); fireEvent.click(await screen.findByRole('checkbox', { name: /依据语言/ })); const practice = await screen.findByRole('checkbox', { name: /固定练习241/ }); fireEvent.click(practice); expect(screen.getByLabelText('教案班级')).toHaveValue('class-241'); expect(screen.getByLabelText('固定学情报告')).toHaveValue('run-241'); const chosen = JSON.parse(screen.getByLabelText('已核验来源结果').textContent!); expect(chosen.classReady).toBe(true); expect(chosen.practiceRevisionIds).toEqual(['practice-fixed-241']); expect(sources.listClasses.mock.calls).toEqual([[{ status: 'active', offset: 0, limit: 200 }], [{ status: 'active', offset: 200, limit: 200 }]]); expect(sources.listRuns.mock.calls).toEqual([[{ offset: 0, limit: 200 }], [{ offset: 200, limit: 200 }]]); expect(sources.listPractices.mock.calls).toEqual([[{ analysisRunId: 'run-241', offset: 0, limit: 200 }], [{ analysisRunId: 'run-241', offset: 200, limit: 200 }]]);
  });
  it.each((['classes', 'runs', 'practices'] as const).flatMap((kind) => (['failure', 'empty', 'invalid-total', 'changed-total', 'wrong-offset'] as const).map((fault) => [kind, fault] as const)))('%s later-page %s stays visible without adopting a partial source', async (kind, fault) => {
    const sources = completeSourceFixture(kind, fault); localSourceHost(sources); await openSourcePanel(); if (kind === 'practices') await chooseLaterReport(); const alert = await screen.findByRole('alert'); expect(alert.textContent).toMatch(fault === 'failure' ? /后页读取失败/ : /分页/); expect(sources[kind === 'classes' ? 'listClasses' : kind === 'runs' ? 'listRuns' : 'listPractices']).toHaveBeenCalledTimes(2); expect(JSON.parse(screen.getByLabelText('已核验来源结果').textContent!).classReady).toBe(false); expect(screen.queryByRole('checkbox', { name: /固定练习241/ })).not.toBeInTheDocument(); if (kind !== 'practices') { expect(screen.queryByRole('option', { name: '班级1' })).not.toBeInTheDocument(); expect(screen.queryByRole('option', { name: /报告241/ })).not.toBeInTheDocument(); } else expect(screen.queryByRole('checkbox', { name: /依据语言/ })).not.toBeInTheDocument();
  });
  it('a late old class page cannot replace a newer explicit source refresh', async () => {
    let finish!: (value: ReturnType<typeof realPage<ClassView>>) => void; const rows = Array.from({ length: 241 }, (_, index) => classItem(index + 1)); const sources = completeSourceFixture(); sources.listClasses.mockImplementationOnce(async (query) => realPage(rows, query)).mockImplementationOnce(() => new Promise((resolve) => { finish = resolve; })).mockImplementation(async (query) => realPage([{ ...classItem(900), name: '当前新列表' }], query)); localSourceHost(sources); await openSourcePanel(); await waitFor(() => expect(sources.listClasses).toHaveBeenCalledTimes(2)); fireEvent.click(screen.getByRole('button', { name: '刷新来源列表' })); await screen.findByRole('option', { name: '当前新列表' }); await act(async () => finish(realPage(rows, { offset: 200, limit: 200 }))); expect(screen.getByRole('option', { name: '当前新列表' })).toBeInTheDocument(); expect(screen.queryByRole('option', { name: '班级241' })).not.toBeInTheDocument(); expect(sources.listClasses).toHaveBeenCalledTimes(3);
  });
  it('a source-list page resolving after unmount performs no further reads', async () => {
    let finish!: (value: ReturnType<typeof realPage<ClassView>>) => void; const rows = Array.from({ length: 241 }, (_, index) => classItem(index + 1)); const sources = completeSourceFixture(); sources.listClasses.mockImplementationOnce(async (query) => realPage(rows, query)).mockImplementationOnce(() => new Promise((resolve) => { finish = resolve; })); const workspace = localSourceHost(sources); await openSourcePanel(); await waitFor(() => expect(sources.listClasses).toHaveBeenCalledTimes(2)); workspace.unmount(); await act(async () => finish(realPage(rows, { offset: 200, limit: 200 }))); expect(sources.listClasses).toHaveBeenCalledTimes(2);
  });
});

function PendingDocumentUIHarness() {
  const editor = useLessonEditor(), doc = useLessonDocument(); const [result, setResult] = useState('尚未决定');
  if (!editor.ready) return <p>正在恢复状态同步隔离稿</p>;
  return <><LeaveProtection /><input aria-label="操作期间的本地正文" value={editor.data.title} onChange={(event) => editor.set({ title: event.target.value })} /><button onClick={() => doc.setSelection({ subjectId: 'chinese', classId: 'class-a', context: null })}>明确状态同步文档来源</button><DocumentsPanel /><button onClick={async () => setResult(await doc.leave.current?.() ? '允许离开' : '保持当前稿')}>请求状态同步离开</button><output aria-label="状态同步离开结果">{result}</output></>;
}
function pendingDocumentUIHost(api: typeof lessonPlanApi, strict = false) { const fixture = <NavigationPreference><DocumentGateway services={{ repository: leaveRepository(), lessonApi: api }}><PendingDocumentUIHarness /></DocumentGateway></NavigationPreference>; return render(strict ? <StrictMode>{fixture}</StrictMode> : fixture); }
async function startPendingDocument(kind: 'create' | 'import') { await screen.findByLabelText('操作期间的本地正文'); fireEvent.click(screen.getByRole('button', { name: '明确状态同步文档来源' })); fireEvent.click(screen.getByRole('button', { name: kind === 'create' ? '创建空白后台教案' : '导入完整旧本地稿到后台' })); }
const importOperationKey = 'zhiqikeyuan:lesson-plan:operation:v1:import';
describe('F30-L v6 real document operation notification keeps an open leave dialog current', () => {
  it.each(['create', 'import'] as const)('%s busy to unknown updates the existing dialog without another edit or reopen', async (kind) => {
    let reject!: (error: ApiError) => void; const send = vi.fn<(body: Parameters<typeof lessonPlanApi.createLesson>[0] | Parameters<typeof lessonPlanApi.importLocalLesson>[0]) => Promise<LessonView>>(() => new Promise<LessonView>((_resolve, fail) => { reject = fail; })); const api = services(kind === 'create' ? { createLesson: send } : { importLocalLesson: send }); pendingDocumentUIHost(api); await startPendingDocument(kind); await waitFor(() => expect(send).toHaveBeenCalledTimes(1)); const key = kind === 'import' ? importOperationKey : 'zhiqikeyuan:lesson-plan:operation:v1:create'; const cached = localStorage.getItem(key); fireEvent.change(screen.getByLabelText('操作期间的本地正文'), { target: { value: 'HTTP期间教师的最新正文' } }); fireEvent.click(screen.getByRole('button', { name: '请求状态同步离开' })); const opened = await screen.findByRole('dialog', { name: '离开当前教案' }); expect(screen.getByRole('button', { name: '保存成功后离开' })).toBeDisabled(); expect(screen.getByRole('button', { name: '保留恢复缓存后离开' })).toBeDisabled(); await act(async () => reject(new ApiError('NETWORK_ERROR', '首个响应丢失', 0, true))); expect(screen.getByText(/原操作结果未知；请重试原包后再保存或放弃/)).toBeInTheDocument(); expect(screen.getByRole('dialog', { name: '离开当前教案' })).toBe(opened); expect(screen.getByRole('button', { name: '保存成功后离开' })).toBeDisabled(); expect(screen.getByRole('button', { name: '明确放弃未保存编辑后离开' })).toBeDisabled(); expect(screen.getByRole('button', { name: '保留恢复缓存后离开' })).toBeEnabled(); expect(screen.getByRole('button', { name: kind === 'import' ? '重试原导入包' : '重试原创建包' })).toBeEnabled(); expect(screen.getByLabelText('操作期间的本地正文')).toHaveValue('HTTP期间教师的最新正文'); expect(localStorage.getItem(key)).toBe(cached); expect(router.push).not.toHaveBeenCalled(); if (kind === 'import') expect(send.mock.calls[0][0]).toMatchObject({ draft: leaveLocalDraft(), submissionId: expect.any(String) });
  });
  it.each([422, 503])('unknown import retry busy to known failure%s updates the same dialog and replays the exact first body', async (status) => {
    let rejectFirst!: (error: ApiError) => void, rejectRetry!: (error: ApiError) => void; const cachedBeforeSend: string[] = []; const importLocalLesson = vi.fn<typeof lessonPlanApi.importLocalLesson>().mockImplementationOnce(() => { cachedBeforeSend.push(localStorage.getItem(importOperationKey)!); return new Promise((_resolve, fail) => { rejectFirst = fail; }); }).mockImplementationOnce(() => { cachedBeforeSend.push(localStorage.getItem(importOperationKey)!); return new Promise((_resolve, fail) => { rejectRetry = fail; }); }); pendingDocumentUIHost(services({ importLocalLesson })); await startPendingDocument('import'); await waitFor(() => expect(importLocalLesson).toHaveBeenCalledTimes(1)); fireEvent.change(screen.getByLabelText('操作期间的本地正文'), { target: { value: '原包之外的后来编辑' } }); fireEvent.click(screen.getByRole('button', { name: '请求状态同步离开' })); const opened = await screen.findByRole('dialog', { name: '离开当前教案' }); await act(async () => rejectFirst(new ApiError('NETWORK_ERROR', '导入ACK丢失', 0, true))); expect(screen.getByText(/原操作结果未知；请重试原包后再保存或放弃/)).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: '重试原导入包' })); await waitFor(() => expect(importLocalLesson).toHaveBeenCalledTimes(2)); expect(screen.queryByText(/原操作结果未知；请重试原包后再保存或放弃/)).not.toBeInTheDocument(); expect(screen.getByRole('button', { name: '保留恢复缓存后离开' })).toBeDisabled(); expect(importLocalLesson.mock.calls[1]).toEqual(importLocalLesson.mock.calls[0]); expect(cachedBeforeSend[1]).toBe(cachedBeforeSend[0]); await act(async () => rejectRetry(new ApiError('VALIDATION', '原包明确失败', status, status === 503))); await screen.findByText('原包明确失败'); expect(screen.getByRole('dialog', { name: '离开当前教案' })).toBe(opened); expect(screen.queryByText(/原操作结果未知；请重试原包后再保存或放弃/)).not.toBeInTheDocument(); expect(screen.getByRole('button', { name: '保存成功后离开' })).toBeEnabled(); expect(screen.getByRole('button', { name: '明确放弃未保存编辑后离开' })).toBeEnabled(); expect(screen.getByLabelText('操作期间的本地正文')).toHaveValue('原包之外的后来编辑'); expect(localStorage.getItem(importOperationKey)).toBeNull(); expect(router.push).not.toHaveBeenCalled();
  });
  it('known success updates the open decision before navigating and saves the latest local edit only after explicit approval', async () => {
    let rejectFirst!: (error: ApiError) => void, finishRetry!: (next: LessonView) => void; const importLocalLesson = vi.fn<typeof lessonPlanApi.importLocalLesson>().mockImplementationOnce(() => new Promise((_resolve, fail) => { rejectFirst = fail; })).mockImplementationOnce(() => new Promise((resolve) => { finishRetry = resolve; })); pendingDocumentUIHost(services({ importLocalLesson })); await startPendingDocument('import'); await waitFor(() => expect(importLocalLesson).toHaveBeenCalledTimes(1)); fireEvent.change(screen.getByLabelText('操作期间的本地正文'), { target: { value: '已导入原稿之后的新输入' } }); fireEvent.click(screen.getByRole('button', { name: '请求状态同步离开' })); const opened = await screen.findByRole('dialog', { name: '离开当前教案' }); await act(async () => rejectFirst(new ApiError('NETWORK_ERROR', 'ACK未知', 0, true))); expect(screen.getByText(/原操作结果未知；请重试原包后再保存或放弃/)).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: '重试原导入包' })); await waitFor(() => expect(importLocalLesson).toHaveBeenCalledTimes(2)); await act(async () => finishRetry(view('imported-fixed'))); await waitFor(() => expect(screen.getByRole('button', { name: '保存成功后离开' })).toBeEnabled()); expect(screen.getByRole('dialog', { name: '离开当前教案' })).toBe(opened); expect(router.push).not.toHaveBeenCalled(); expect(importLocalLesson.mock.calls[1]).toEqual(importLocalLesson.mock.calls[0]); expect(screen.getByLabelText('操作期间的本地正文')).toHaveValue('已导入原稿之后的新输入'); fireEvent.click(screen.getByRole('button', { name: '保存成功后离开' })); await waitFor(() => expect(router.push).toHaveBeenCalledWith('/lesson-plans?lessonPlanId=imported-fixed')); expect(JSON.parse(localStorage.getItem(LEGACY_KEY)!).data.title).toBe('已导入原稿之后的新输入'); expect(localStorage.getItem(importOperationKey)).toBeNull(); expect(importLocalLesson).toHaveBeenCalledTimes(2);
  });
  it('an old producer receipt after teardown cannot clear the recovered current unknown operation under StrictMode', async () => {
    let finishOld!: (next: LessonView) => void; const importLocalLesson = vi.fn<typeof lessonPlanApi.importLocalLesson>(() => new Promise((resolve) => { finishOld = resolve; })); const api = services({ importLocalLesson }); const first = pendingDocumentUIHost(api); await startPendingDocument('import'); await waitFor(() => expect(importLocalLesson).toHaveBeenCalledTimes(1)); const original = localStorage.getItem(importOperationKey); first.unmount(); pendingDocumentUIHost(api, true); await screen.findByLabelText('操作期间的本地正文'); await screen.findByRole('button', { name: '重试原导入包' }); fireEvent.click(screen.getByRole('button', { name: '请求状态同步离开' })); const opened = await screen.findByRole('dialog', { name: '离开当前教案' }); expect(screen.getByText(/原操作结果未知；请重试原包后再保存或放弃/)).toBeInTheDocument(); await act(async () => finishOld(view('late-old-import'))); expect(screen.getByRole('dialog', { name: '离开当前教案' })).toBe(opened); expect(screen.getByText(/原操作结果未知；请重试原包后再保存或放弃/)).toBeInTheDocument(); expect(screen.getByRole('button', { name: '保存成功后离开' })).toBeDisabled(); expect(screen.getByRole('button', { name: '明确放弃未保存编辑后离开' })).toBeDisabled(); expect(localStorage.getItem(importOperationKey)).toBe(original); expect(router.push).not.toHaveBeenCalled(); expect(importLocalLesson).toHaveBeenCalledTimes(1);
  });
});

function sourceProfile(id: string): ModelProfileView { return { id, connectionId: 'isolated-connection', displayName: id === 'model-a' ? '模型M1' : '模型M2', modelId: id, purpose: 'lesson', contextTokens: null, maxOutputTokens: null, supportedParams: [], reasoningEnabled: null, reasoningEffort: null, reasoningStyle: null, capabilities: {}, connection: null, createdAt: '2026-10-03T00:00:00Z', updatedAt: '2026-10-03T00:00:00Z' }; }
function readyPractices() { return [241, 242].map((index) => { const practice = practiceItem(index); const fixed = { ...practice.currentRevision, state: 'reviewed' as const, analysisRunId: 'run-fixed', reviewedAt: '2026-10-03T00:00:00Z' }; return { ...practice, analysisRunId: 'run-fixed', currentRevision: fixed, revisions: [fixed] }; }); }
function raceSources() {
  return { ...defaultSourceApi, listClasses: vi.fn(async () => page([{ ...classItem(1), id: 'class-a', name: '隔离班A' }, { ...classItem(2), id: 'class-b', name: '隔离班B' }])), taxonomy: vi.fn(async () => ({ stages: [], grades: [{ id: 'grade', label: '选定年级', stageId: 'stage' }], subjects: [{ id: 'chinese', label: '语文' }, { id: 'math', label: '数学' }], editions: [{ id: 'edition', label: '选定版本' }] })), listProfiles: vi.fn(async () => [sourceProfile('model-a'), sourceProfile('model-b')]), listRuns: vi.fn(async () => page([fixedRun(), { ...fixedRun(), runId: 'run-next', paperTitle: '新固定报告' }])), getRun: vi.fn<typeof defaultSourceApi.getRun>(async (id) => ({ ...fixedRun(), runId: id })), listClassesReport: vi.fn(async () => page([reportRow('class-a')])), listPractices: vi.fn<typeof defaultSourceApi.listPractices>(async () => page(readyPractices())), listDocuments: vi.fn(async () => ({ documents: [{ documentId: 'textbook', ownerId: 'local-user' as const, title: '受控真实端口教材', libraryIds: [], gradeIds: ['grade'], subjectId: 'chinese', editionId: 'edition', metadataRevisionId: 'meta-fixed', currentRevision: { revisionId: 'doc-fixed', originalFileSha256: 'original-fixed', normalizedTextSha256: 'sha-fixed', parserVersion: 'fixture', charCount: 10, chunkCount: 1, createdAt: '2026-10-03T00:00:00Z' }, pendingRevisionId: null, deletedAt: null, revision: 1 }] })), getDocumentSource: vi.fn(async () => ({ documentRevisionId: 'doc-fixed', normalizedTextSha256: 'sha-fixed', charStart: 0, charEnd: 10, text: '0123456789', locator: { kind: 'markdown' as const, lineStart: 1, lineEnd: 1, pageStart: null, pageEnd: null, blockStart: null, blockEnd: null } })), listConfirmedQuestionRevisions: vi.fn(async () => page([{ questionId: 'question-one', questionRevisionId: 'question-fixed-one', subjectId: 'chinese', stemMarkdown: '同科固定题一' }, { questionId: 'question-two', questionRevisionId: 'question-fixed-two', subjectId: 'chinese', stemMarkdown: '同科固定题二' }])) };
}
function SourceRaceHarness({ proposal = false }: { proposal?: boolean }) { const [inputs, setInputs] = useState(initialGenerationInputs), doc = useLessonDocument(), editor = useLessonEditor(); return <><SourcePanel value={inputs} onChange={setInputs} /><output aria-label="教师与来源输入">{JSON.stringify(inputs)}</output><output aria-label="当前来源选择">{JSON.stringify(doc.selection)}</output>{proposal && editor.server && <ProposalPanel inputs={inputs} />}</>; }
function raceHost(sources: typeof defaultSourceApi, options: { local?: boolean; proposal?: boolean; api?: typeof lessonPlanApi } = {}) { return render(<NavigationPreference><DocumentGateway initialLessonPlanId={options.local ? undefined : 'lesson-a'} services={{ lessonApi: options.api ?? services({ verifyLessonEvidence: vi.fn(async () => evidence) }), sourceApi: sources }}><SourceRaceHarness proposal={options.proposal} /></DocumentGateway></NavigationPreference>); }
function raceInputs() { return JSON.parse(screen.getByLabelText('教师与来源输入').textContent!); }
function chooseTeacherInputs() { fireEvent.change(screen.getByLabelText('教案生成模型'), { target: { value: 'model-a' } }); fireEvent.change(screen.getByLabelText('教案生成模型'), { target: { value: 'model-b' } }); fireEvent.change(screen.getByLabelText('课堂时长'), { target: { value: '43' } }); fireEvent.change(screen.getByLabelText('教案生成要求'), { target: { value: '教师当前的新要求' } }); }
function assertTeacherInputs() { expect(screen.getByLabelText('教案生成模型')).toHaveValue('model-b'); expect(screen.getByLabelText('课堂时长')).toHaveValue(43); expect(screen.getByLabelText('教案生成要求')).toHaveValue('教师当前的新要求'); expect(raceInputs()).toMatchObject({ modelProfileId: 'model-b', durationMinutes: 43, requirements: '教师当前的新要求' }); }
async function verifyRaceEvidence() { fireEvent.change(screen.getByLabelText('教材年级'), { target: { value: 'grade' } }); fireEvent.change(screen.getByLabelText('教材版本'), { target: { value: 'edition' } }); fireEvent.click(screen.getByRole('button', { name: '读取可选教材' })); await screen.findByRole('option', { name: /受控真实端口教材/ }); fireEvent.change(screen.getByLabelText('教材固定修订'), { target: { value: 'textbook' } }); fireEvent.change(screen.getByLabelText('切片终点'), { target: { value: '10' } }); fireEvent.click(screen.getByRole('button', { name: '读取并核验教材切片' })); await waitFor(() => expect(raceInputs().evidence).toEqual(evidence)); }
async function prepareRace(sources: typeof defaultSourceApi, options: { local?: boolean; proposal?: boolean; api?: typeof lessonPlanApi } = {}) { const workspace = raceHost(sources, options); await openSourcePanel(); await screen.findByRole('option', { name: /模型M1/ }); if (options.local) { fireEvent.change(screen.getByLabelText('教案学科'), { target: { value: 'chinese' } }); fireEvent.change(screen.getByLabelText('教案班级'), { target: { value: 'class-a' } }); fireEvent.change(screen.getByLabelText('固定学情报告'), { target: { value: 'run-fixed' } }); fireEvent.click(await screen.findByRole('checkbox', { name: /依据语言/ })); } else await screen.findByRole('checkbox', { name: /依据语言/ }); await waitFor(() => expect(raceInputs().classReady).toBe(true)); fireEvent.change(screen.getByLabelText('教案生成模型'), { target: { value: 'model-a' } }); fireEvent.click(screen.getByRole('button', { name: '读取已确认固定题' })); fireEvent.click(await screen.findByRole('checkbox', { name: /同科固定题一/ })); fireEvent.click(screen.getByRole('checkbox', { name: /固定练习241/ })); await verifyRaceEvidence(); return workspace; }
describe('F30-L v4 late source reads retain current teacher inputs', () => {
  it('initial report completion retains an actual M1 to M2 selection, duration and requirements', async () => {
    let finish!: (run: AnalysisRunView) => void; const sources = raceSources(); sources.getRun.mockImplementationOnce(() => new Promise((resolve) => { finish = resolve; })); raceHost(sources); await openSourcePanel(); await screen.findByRole('option', { name: /模型M1/ }); await waitFor(() => expect(sources.getRun).toHaveBeenCalledTimes(1)); chooseTeacherInputs(); await act(async () => finish(fixedRun())); await screen.findByRole('checkbox', { name: /依据语言/ }); assertTeacherInputs(); expect(raceInputs().classReady).toBe(true);
  });
  it.each(['classes', 'report', 'practices'])('same-source refresh paused at %s keeps new teacher inputs, evidence and legal selections', async (stage) => {
    const sources = raceSources(); await prepareRace(sources); let finish!: () => void;
    if (stage === 'classes') sources.listClasses.mockImplementationOnce(() => new Promise((resolve) => { finish = () => resolve(page([{ ...classItem(1), id: 'class-a', name: '隔离班A' }])); }));
    if (stage === 'report') sources.getRun.mockImplementationOnce(() => new Promise((resolve) => { finish = () => resolve(fixedRun()); }));
    if (stage === 'practices') sources.listPractices.mockImplementationOnce(() => new Promise((resolve) => { finish = () => resolve(page(readyPractices())); }));
    fireEvent.click(screen.getByRole('button', { name: '刷新来源列表' })); await waitFor(() => expect(typeof finish).toBe('function')); chooseTeacherInputs(); fireEvent.click(screen.getByRole('checkbox', { name: /同科固定题二/ })); fireEvent.click(screen.getByRole('checkbox', { name: /固定练习242/ })); await act(async () => finish()); await waitFor(() => expect(raceInputs().classReady).toBe(true)); assertTeacherInputs(); expect(raceInputs().questionRevisionIds).toEqual(['question-fixed-one', 'question-fixed-two']); expect(raceInputs().practiceRevisionIds).toEqual(['practice-fixed-241', 'practice-fixed-242']); expect(raceInputs().evidence).toEqual(evidence); expect(JSON.parse(screen.getByLabelText('当前来源选择').textContent!)).toEqual({ subjectId: 'chinese', classId: 'class-a', context: { analysisRunId: 'run-fixed', selectedKnowledgePointIds: ['kp-one'] } });
  });
  it.each([0, 503])('late report failure status%s keeps current teacher inputs and prior complete source', async (status) => {
    const sources = raceSources(); await prepareRace(sources); let reject!: (error: ApiError) => void; sources.getRun.mockImplementationOnce(() => new Promise((_resolve, fail) => { reject = fail; })); fireEvent.click(screen.getByRole('button', { name: '刷新来源列表' })); await waitFor(() => expect(typeof reject).toBe('function')); chooseTeacherInputs(); await act(async () => reject(new ApiError('READ_FAILED', '受控来源读取失败', status, true))); await screen.findByText('受控来源读取失败'); assertTeacherInputs(); expect(raceInputs().evidence).toEqual(evidence); expect(raceInputs().questionRevisionIds).toEqual(['question-fixed-one']); expect(raceInputs().practiceRevisionIds).toEqual(['practice-fixed-241']);
  });
  it('a cancelled old source read cannot replace the newly selected report or current inputs', async () => {
    const sources = raceSources(); await prepareRace(sources); let finish!: (run: AnalysisRunView) => void; sources.getRun.mockImplementationOnce(() => new Promise((resolve) => { finish = resolve; })); fireEvent.click(screen.getByRole('button', { name: '刷新来源列表' })); await waitFor(() => expect(typeof finish).toBe('function')); chooseTeacherInputs(); fireEvent.change(screen.getByLabelText('固定学情报告'), { target: { value: 'run-next' } }); await waitFor(() => expect(screen.getByLabelText('固定学情报告')).toHaveValue('run-next')); await act(async () => finish(fixedRun())); expect(screen.getByLabelText('固定学情报告')).toHaveValue('run-next'); assertTeacherInputs(); expect(raceInputs().practiceRevisionIds).toEqual([]); expect(raceInputs().evidence).toBeNull();
  });
  it.each(['report', 'subject'])('a genuine %s switch clears only invalid source-bound choices and retains teacher inputs', async (change) => {
    const sources = raceSources(); await prepareRace(sources, { local: true }); chooseTeacherInputs(); if (change === 'subject') fireEvent.change(screen.getByLabelText('教案学科'), { target: { value: 'math' } }); else { fireEvent.change(screen.getByLabelText('固定学情报告'), { target: { value: 'run-next' } }); await waitFor(() => expect(screen.getByLabelText('固定学情报告')).toHaveValue('run-next')); } assertTeacherInputs(); expect(raceInputs().evidence).toBeNull(); expect(raceInputs().practiceRevisionIds).toEqual([]); expect(raceInputs().questionRevisionIds).toEqual(change === 'subject' ? [] : ['question-fixed-one']); expect(raceInputs().classReady).toBe(false);
  });
  it('a late evidence verification after new teacher inputs stays invalid and does not overwrite them', async () => {
    const sources = raceSources(); let finish!: (verified: LessonEvidenceView) => void; const api = services({ verifyLessonEvidence: vi.fn(() => new Promise<LessonEvidenceView>((resolve) => { finish = resolve; })) }); raceHost(sources, { api }); await openSourcePanel(); await screen.findByRole('checkbox', { name: /依据语言/ }); fireEvent.change(screen.getByLabelText('教材年级'), { target: { value: 'grade' } }); fireEvent.change(screen.getByLabelText('教材版本'), { target: { value: 'edition' } }); fireEvent.click(screen.getByRole('button', { name: '读取可选教材' })); await screen.findByRole('option', { name: /受控真实端口教材/ }); fireEvent.change(screen.getByLabelText('教材固定修订'), { target: { value: 'textbook' } }); fireEvent.change(screen.getByLabelText('切片终点'), { target: { value: '10' } }); fireEvent.click(screen.getByRole('button', { name: '读取并核验教材切片' })); await waitFor(() => expect(api.verifyLessonEvidence).toHaveBeenCalledTimes(1)); chooseTeacherInputs(); await act(async () => finish(evidence)); assertTeacherInputs(); expect(raceInputs().evidence).toBeNull();
  });
  it('model changed during source refresh remains M2 and keeps a selected M1 candidate stale', async () => {
    const sources = raceSources(); const applyLessonProposal = vi.fn<typeof lessonPlanApi.applyLessonProposal>(async () => view('lesson-a', 2)); const api = services({ verifyLessonEvidence: vi.fn(async () => evidence), generateLessonProposal: vi.fn(async () => generationReceipt()), getLessonProposal: vi.fn(async () => candidate()), applyLessonProposal }); await prepareRace(sources, { proposal: true, api }); const generate = screen.getByRole('button', { name: '保存当前稿并生成 AI 候选' }); await waitFor(() => expect(generate).toBeEnabled()); fireEvent.click(generate); fireEvent.click(await screen.findByLabelText('采用核心素养')); let finish!: (run: AnalysisRunView) => void; sources.getRun.mockImplementationOnce(() => new Promise((resolve) => { finish = resolve; })); fireEvent.click(screen.getByRole('button', { name: '刷新来源列表' })); await waitFor(() => expect(typeof finish).toBe('function')); chooseTeacherInputs(); await act(async () => finish(fixedRun())); assertTeacherInputs(); expect(screen.getByText(/固定候选 proposal-fixed · 已过期/)).toBeInTheDocument(); expect(screen.getByLabelText('采用核心素养')).toBeChecked(); expect(screen.getByRole('button', { name: '仅采用所选完整字段' })).toBeDisabled(); fireEvent.click(screen.getByRole('button', { name: '仅采用所选完整字段' })); expect(applyLessonProposal).not.toHaveBeenCalled();
  });
});
