import type { AnalysisRunView, ClassReportRow, EvidenceRow, Page, PracticeSetView, PracticeSuggestion, PracticeRevisionView } from '@/contracts/b4';
import type { RichContentV2 } from '@/contracts/teaching-loop';

export const rich: RichContentV2 = { version: 2, sharedMaterials: [{ id: 'material', blocks: [{ id: 'm1', kind: 'paragraph', text: '固定共同材料' }] }], stemBlocks: [{ id: 'b1', kind: 'paragraph', text: '固定题干' }], optionBlocks: { A: [{ id: 'o1', kind: 'paragraph', text: '固定选项' }] }, answerBlocks: [{ id: 'a1', kind: 'paragraph', text: '教师答案甲' }], explanationBlocks: [{ id: 'e1', kind: 'paragraph', text: '教师解析乙' }], assets: [], origin: { originalAssetId: 'source', originalSha256: 'source-sha', sourceLocator: { paragraph: 1 } } };
export const point = { knowledgePointId: 'kp-1', knowledgeRevisionId: 'kr-1', name: '固定知识点', role: 'primary' as const };
export const participant = { participantId: 'pa', studentId: 'student-a', studentNo: '001', name: '甲', classId: 'class-a', className: null, classNameNote: '该成绩未记录班名' as const, attemptNo: 1, attendance: 'present' as const };
export const run: AnalysisRunView = { runId: 'run-old', assessmentId: 'assessment-old', subjectId: 'math', scoreRevisionId: 'score-old', paperRevisionId: 'paper-old', paperTitle: '固定原卷', inputHash: 'hash', ruleCode: 'any_loss_v1', selectionSnapshot: { selectedParticipantIds: ['pa'], uniqueStudentCount: 1, participantCount: 1, leafCount: 2, stateCounts: { recorded: 1, missing: 1, absent: 0, exempt: 0 } }, participants: [participant], knowledgePoints: [point], job: { jobId: 'analysis-job', domain: 'teaching', kind: 'analysis', state: 'succeeded', attempt: 1, result: { runId: 'run-old' }, error: null }, reportReady: true, createdAt: '2026-10-02' };
export const classRow: ClassReportRow = { classId: 'class-a', className: null, classNameNote: '该成绩未记录班名', knowledgePoint: point, selectedCount: 4, validCount: 3, needsCount: 2, incompleteCount: 2, noEvidenceCount: 1, fullCreditCount: 1, numerator: 2, denominator: 3, ratio: 0.123456 };
export const evidenceRow: EvidenceRow = { evidenceId: 'ev-1', runId: run.runId, scoreRevisionId: run.scoreRevisionId, paperRevisionId: run.paperRevisionId, participant, itemId: 'leaf-a', itemPath: '1(1)', maxScoreUnits: 100, scoreUnits: 0, status: 'recorded', knowledgePoints: [point], content: { ...rich }, sharedMaterials: rich.sharedMaterials.map((material) => ({ ...material })), sourceLocator: { paragraph: 1 }, assets: [], practiceRevisionId: null, practiceItemId: null, associationNote: '' };
export const suggestion: PracticeSuggestion = { questionId: 'question-a', questionRevisionId: 'question-fixed-a', content: rich, knowledgePoints: [point], questionType: 'single_choice', difficulty: 'easy', reason: '覆盖固定目标', answerState: 'complete' };
export const revision: PracticeRevisionView = { practiceSetId: 'practice-a', practiceRevisionId: 'draft-a', version: 1, state: 'draft', title: '固定练习', subjectId: 'math', analysisRunId: run.runId, sourcePaperTitle: '固定原卷', sourceCreatedAt: '2026-10-02T09:30:00Z', targetKnowledgePoints: [point], constraints: { count: 1, questionTypes: [], difficulties: [], includeUnknownDifficulty: false, excludeOriginal: true, deduplicate: true }, inputHash: '', totalScoreUnits: 100, draftItems: [{ itemKey: 'selection-a', questionRevisionId: 'question-fixed-a', ordinal: 1, itemStructure: { nodes: [{ nodeKey: 'node-a', parentNodeKey: null, questionNo: '1', ordinal: 1, isScored: true, maxScore: '1', knowledgePointIds: ['kp-1'], sourceBlockIds: ['b1', 'o1'] }] }, maxScore: '1', selectedKnowledgePointIds: ['kp-1'] }], items: [{ practiceItemId: 'item-a', selectionId: 'selection-a', itemKey: 'selection-a', nodeKey: 'node-a', parentItemId: null, questionNo: '1', ordinal: 1, isScored: true, maxScoreUnits: 100, questionId: 'question-a', questionRevisionId: 'question-fixed-a', content: rich, knowledgePoints: [point], sourceLocator: {}, reason: '明确选题', answerState: 'complete' }], reviewedAt: null, createdAt: '2026-10-02' };
export const practice: PracticeSetView = { practiceSetId: 'practice-a', title: revision.title, subjectId: 'math', analysisRunId: run.runId, sourcePaperTitle: revision.sourcePaperTitle, sourceCreatedAt: revision.sourceCreatedAt, revision: 1, currentRevision: revision, revisions: [revision], replayed: false };
export function page<T>(items: T[], offset = 0, total = items.length): Page<T> { return { items, total, offset, limit: 50 }; }
export function deferred<T>() { let resolve!: (value: T) => void; let reject!: (cause: unknown) => void; const promise = new Promise<T>((yes, no) => { resolve = yes; reject = no; }); return { promise, resolve, reject }; }
